// @generated by `cargo xtask codegen` from the vendored OCPP JSON schemas.
// DO NOT EDIT — re-run the generator instead. CI fails if this file is stale.

//! Enumerations defined by OCPP 1.6, generated from the official JSON schemas.

#![allow(unused_imports, clippy::doc_markdown, clippy::struct_excessive_bools)]
#![allow(
    clippy::too_many_lines,
    clippy::too_many_arguments,
    clippy::wildcard_imports
)]
#![allow(clippy::match_same_arms, clippy::fn_params_excessive_bools)]

use alloc::string::String;
use alloc::vec::Vec;

use crate::ocpp_enum;

ocpp_enum! {
    /// The OCPP 1.6 `AuthorizationStatus` enumeration.
    AuthorizationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Blocked`.
        Blocked = "Blocked",
        /// `Expired`.
        Expired = "Expired",
        /// `Invalid`.
        Invalid = "Invalid",
        /// `ConcurrentTx`.
        ConcurrentTx = "ConcurrentTx",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `AvailabilityStatus` enumeration.
    AvailabilityStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Scheduled`.
        Scheduled = "Scheduled",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `AvailabilityType` enumeration.
    AvailabilityType {
        /// `Inoperative`.
        Inoperative = "Inoperative",
        /// `Operative`.
        Operative = "Operative",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `CancelReservationStatus` enumeration.
    CancelReservationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `CertificateSignedStatus` enumeration.
    CertificateSignedStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `CertificateUse` enumeration.
    CertificateUse {
        /// `CentralSystemRootCertificate`.
        CentralSystemRootCertificate = "CentralSystemRootCertificate",
        /// `ManufacturerRootCertificate`.
        ManufacturerRootCertificate = "ManufacturerRootCertificate",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ChargePointErrorCode` enumeration.
    ChargePointErrorCode {
        /// `ConnectorLockFailure`.
        ConnectorLockFailure = "ConnectorLockFailure",
        /// `EVCommunicationError`.
        EVCommunicationError = "EVCommunicationError",
        /// `GroundFailure`.
        GroundFailure = "GroundFailure",
        /// `HighTemperature`.
        HighTemperature = "HighTemperature",
        /// `InternalError`.
        InternalError = "InternalError",
        /// `LocalListConflict`.
        LocalListConflict = "LocalListConflict",
        /// `NoError`.
        NoError = "NoError",
        /// `OtherError`.
        OtherError = "OtherError",
        /// `OverCurrentFailure`.
        OverCurrentFailure = "OverCurrentFailure",
        /// `PowerMeterFailure`.
        PowerMeterFailure = "PowerMeterFailure",
        /// `PowerSwitchFailure`.
        PowerSwitchFailure = "PowerSwitchFailure",
        /// `ReaderFailure`.
        ReaderFailure = "ReaderFailure",
        /// `ResetFailure`.
        ResetFailure = "ResetFailure",
        /// `UnderVoltage`.
        UnderVoltage = "UnderVoltage",
        /// `OverVoltage`.
        OverVoltage = "OverVoltage",
        /// `WeakSignal`.
        WeakSignal = "WeakSignal",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ChargePointStatus` enumeration.
    ChargePointStatus {
        /// `Available`.
        Available = "Available",
        /// `Preparing`.
        Preparing = "Preparing",
        /// `Charging`.
        Charging = "Charging",
        /// `SuspendedEVSE`.
        SuspendedEVSE = "SuspendedEVSE",
        /// `SuspendedEV`.
        SuspendedEV = "SuspendedEV",
        /// `Finishing`.
        Finishing = "Finishing",
        /// `Reserved`.
        Reserved = "Reserved",
        /// `Unavailable`.
        Unavailable = "Unavailable",
        /// `Faulted`.
        Faulted = "Faulted",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ChargingProfileKind` enumeration.
    ChargingProfileKind {
        /// `Absolute`.
        Absolute = "Absolute",
        /// `Recurring`.
        Recurring = "Recurring",
        /// `Relative`.
        Relative = "Relative",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ChargingProfilePurpose` enumeration.
    ChargingProfilePurpose {
        /// `ChargePointMaxProfile`.
        ChargePointMaxProfile = "ChargePointMaxProfile",
        /// `TxDefaultProfile`.
        TxDefaultProfile = "TxDefaultProfile",
        /// `TxProfile`.
        TxProfile = "TxProfile",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ChargingProfileStatus` enumeration.
    ChargingProfileStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotSupported`.
        NotSupported = "NotSupported",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ChargingRateUnit` enumeration.
    ChargingRateUnit {
        /// `A`.
        A = "A",
        /// `W`.
        W = "W",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ClearCacheStatus` enumeration.
    ClearCacheStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ClearChargingProfileStatus` enumeration.
    ClearChargingProfileStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Unknown`.
        Unknown = "Unknown",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ConfigurationStatus` enumeration.
    ConfigurationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `RebootRequired`.
        RebootRequired = "RebootRequired",
        /// `NotSupported`.
        NotSupported = "NotSupported",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `DataTransferStatus` enumeration.
    DataTransferStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `UnknownMessageId`.
        UnknownMessageId = "UnknownMessageId",
        /// `UnknownVendorId`.
        UnknownVendorId = "UnknownVendorId",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `DeleteCertificateStatus` enumeration.
    DeleteCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
        /// `NotFound`.
        NotFound = "NotFound",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `DiagnosticsStatus` enumeration.
    DiagnosticsStatus {
        /// `Idle`.
        Idle = "Idle",
        /// `Uploaded`.
        Uploaded = "Uploaded",
        /// `UploadFailed`.
        UploadFailed = "UploadFailed",
        /// `Uploading`.
        Uploading = "Uploading",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ExtendedMessageTrigger` enumeration.
    ExtendedMessageTrigger {
        /// `BootNotification`.
        BootNotification = "BootNotification",
        /// `LogStatusNotification`.
        LogStatusNotification = "LogStatusNotification",
        /// `FirmwareStatusNotification`.
        FirmwareStatusNotification = "FirmwareStatusNotification",
        /// `Heartbeat`.
        Heartbeat = "Heartbeat",
        /// `MeterValues`.
        MeterValues = "MeterValues",
        /// `SignChargePointCertificate`.
        SignChargePointCertificate = "SignChargePointCertificate",
        /// `StatusNotification`.
        StatusNotification = "StatusNotification",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `FirmwareStatus` enumeration.
    FirmwareStatus {
        /// `Downloaded`.
        Downloaded = "Downloaded",
        /// `DownloadFailed`.
        DownloadFailed = "DownloadFailed",
        /// `Downloading`.
        Downloading = "Downloading",
        /// `Idle`.
        Idle = "Idle",
        /// `InstallationFailed`.
        InstallationFailed = "InstallationFailed",
        /// `Installing`.
        Installing = "Installing",
        /// `Installed`.
        Installed = "Installed",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `GenericStatus` enumeration.
    GenericStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `GetCompositeScheduleStatus` enumeration.
    GetCompositeScheduleStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `GetInstalledCertificateStatus` enumeration.
    GetInstalledCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `NotFound`.
        NotFound = "NotFound",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `HashAlgorithm` enumeration.
    HashAlgorithm {
        /// `SHA256`.
        SHA256 = "SHA256",
        /// `SHA384`.
        SHA384 = "SHA384",
        /// `SHA512`.
        SHA512 = "SHA512",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `InstallCertificateStatus` enumeration.
    InstallCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `Location` enumeration.
    Location {
        /// `Cable`.
        Cable = "Cable",
        /// `EV`.
        EV = "EV",
        /// `Inlet`.
        Inlet = "Inlet",
        /// `Outlet`.
        Outlet = "Outlet",
        /// `Body`.
        Body = "Body",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `LogStatus` enumeration.
    LogStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `AcceptedCanceled`.
        AcceptedCanceled = "AcceptedCanceled",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `LogType` enumeration.
    LogType {
        /// `DiagnosticsLog`.
        DiagnosticsLog = "DiagnosticsLog",
        /// `SecurityLog`.
        SecurityLog = "SecurityLog",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `Measurand` enumeration.
    Measurand {
        /// `Energy.Active.Export.Register`.
        EnergyActiveExportRegister = "Energy.Active.Export.Register",
        /// `Energy.Active.Import.Register`.
        EnergyActiveImportRegister = "Energy.Active.Import.Register",
        /// `Energy.Reactive.Export.Register`.
        EnergyReactiveExportRegister = "Energy.Reactive.Export.Register",
        /// `Energy.Reactive.Import.Register`.
        EnergyReactiveImportRegister = "Energy.Reactive.Import.Register",
        /// `Energy.Active.Export.Interval`.
        EnergyActiveExportInterval = "Energy.Active.Export.Interval",
        /// `Energy.Active.Import.Interval`.
        EnergyActiveImportInterval = "Energy.Active.Import.Interval",
        /// `Energy.Reactive.Export.Interval`.
        EnergyReactiveExportInterval = "Energy.Reactive.Export.Interval",
        /// `Energy.Reactive.Import.Interval`.
        EnergyReactiveImportInterval = "Energy.Reactive.Import.Interval",
        /// `Power.Active.Export`.
        PowerActiveExport = "Power.Active.Export",
        /// `Power.Active.Import`.
        PowerActiveImport = "Power.Active.Import",
        /// `Power.Offered`.
        PowerOffered = "Power.Offered",
        /// `Power.Reactive.Export`.
        PowerReactiveExport = "Power.Reactive.Export",
        /// `Power.Reactive.Import`.
        PowerReactiveImport = "Power.Reactive.Import",
        /// `Power.Factor`.
        PowerFactor = "Power.Factor",
        /// `Current.Import`.
        CurrentImport = "Current.Import",
        /// `Current.Export`.
        CurrentExport = "Current.Export",
        /// `Current.Offered`.
        CurrentOffered = "Current.Offered",
        /// `Voltage`.
        Voltage = "Voltage",
        /// `Frequency`.
        Frequency = "Frequency",
        /// `Temperature`.
        Temperature = "Temperature",
        /// `SoC`.
        SoC = "SoC",
        /// `RPM`.
        RPM = "RPM",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `MessageTrigger` enumeration.
    MessageTrigger {
        /// `BootNotification`.
        BootNotification = "BootNotification",
        /// `DiagnosticsStatusNotification`.
        DiagnosticsStatusNotification = "DiagnosticsStatusNotification",
        /// `FirmwareStatusNotification`.
        FirmwareStatusNotification = "FirmwareStatusNotification",
        /// `Heartbeat`.
        Heartbeat = "Heartbeat",
        /// `MeterValues`.
        MeterValues = "MeterValues",
        /// `StatusNotification`.
        StatusNotification = "StatusNotification",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `Phase` enumeration.
    Phase {
        /// `L1`.
        L1 = "L1",
        /// `L2`.
        L2 = "L2",
        /// `L3`.
        L3 = "L3",
        /// `N`.
        N = "N",
        /// `L1-N`.
        L1N = "L1-N",
        /// `L2-N`.
        L2N = "L2-N",
        /// `L3-N`.
        L3N = "L3-N",
        /// `L1-L2`.
        L1L2 = "L1-L2",
        /// `L2-L3`.
        L2L3 = "L2-L3",
        /// `L3-L1`.
        L3L1 = "L3-L1",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ReadingContext` enumeration.
    ReadingContext {
        /// `Interruption.Begin`.
        InterruptionBegin = "Interruption.Begin",
        /// `Interruption.End`.
        InterruptionEnd = "Interruption.End",
        /// `Sample.Clock`.
        SampleClock = "Sample.Clock",
        /// `Sample.Periodic`.
        SamplePeriodic = "Sample.Periodic",
        /// `Transaction.Begin`.
        TransactionBegin = "Transaction.Begin",
        /// `Transaction.End`.
        TransactionEnd = "Transaction.End",
        /// `Trigger`.
        Trigger = "Trigger",
        /// `Other`.
        Other = "Other",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `Reason` enumeration.
    Reason {
        /// `EmergencyStop`.
        EmergencyStop = "EmergencyStop",
        /// `EVDisconnected`.
        EVDisconnected = "EVDisconnected",
        /// `HardReset`.
        HardReset = "HardReset",
        /// `Local`.
        Local = "Local",
        /// `Other`.
        Other = "Other",
        /// `PowerLoss`.
        PowerLoss = "PowerLoss",
        /// `Reboot`.
        Reboot = "Reboot",
        /// `Remote`.
        Remote = "Remote",
        /// `SoftReset`.
        SoftReset = "SoftReset",
        /// `UnlockCommand`.
        UnlockCommand = "UnlockCommand",
        /// `DeAuthorized`.
        DeAuthorized = "DeAuthorized",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `RecurrencyKind` enumeration.
    RecurrencyKind {
        /// `Daily`.
        Daily = "Daily",
        /// `Weekly`.
        Weekly = "Weekly",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `RegistrationStatus` enumeration.
    RegistrationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Pending`.
        Pending = "Pending",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `RemoteStartStopStatus` enumeration.
    RemoteStartStopStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ReservationStatus` enumeration.
    ReservationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Faulted`.
        Faulted = "Faulted",
        /// `Occupied`.
        Occupied = "Occupied",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Unavailable`.
        Unavailable = "Unavailable",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ResetStatus` enumeration.
    ResetStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ResetType` enumeration.
    ResetType {
        /// `Hard`.
        Hard = "Hard",
        /// `Soft`.
        Soft = "Soft",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `SignedFirmwareStatus` enumeration.
    SignedFirmwareStatus {
        /// `Downloaded`.
        Downloaded = "Downloaded",
        /// `DownloadFailed`.
        DownloadFailed = "DownloadFailed",
        /// `Downloading`.
        Downloading = "Downloading",
        /// `DownloadScheduled`.
        DownloadScheduled = "DownloadScheduled",
        /// `DownloadPaused`.
        DownloadPaused = "DownloadPaused",
        /// `Idle`.
        Idle = "Idle",
        /// `InstallationFailed`.
        InstallationFailed = "InstallationFailed",
        /// `Installing`.
        Installing = "Installing",
        /// `Installed`.
        Installed = "Installed",
        /// `InstallRebooting`.
        InstallRebooting = "InstallRebooting",
        /// `InstallScheduled`.
        InstallScheduled = "InstallScheduled",
        /// `InstallVerificationFailed`.
        InstallVerificationFailed = "InstallVerificationFailed",
        /// `InvalidSignature`.
        InvalidSignature = "InvalidSignature",
        /// `SignatureVerified`.
        SignatureVerified = "SignatureVerified",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `TriggerMessageStatus` enumeration.
    TriggerMessageStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotImplemented`.
        NotImplemented = "NotImplemented",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `UnitOfMeasure` enumeration.
    UnitOfMeasure {
        /// `A`.
        A = "A",
        /// `Celcius`.
        Celcius = "Celcius",
        /// `Celsius`.
        Celsius = "Celsius",
        /// `Fahrenheit`.
        Fahrenheit = "Fahrenheit",
        /// `Hertz`.
        Hertz = "Hertz",
        /// `K`.
        K = "K",
        /// `Percent`.
        Percent = "Percent",
        /// `V`.
        V = "V",
        /// `VA`.
        VA = "VA",
        /// `W`.
        W = "W",
        /// `Wh`.
        Wh = "Wh",
        /// `kVA`.
        KVA = "kVA",
        /// `kW`.
        KW = "kW",
        /// `kWh`.
        KWh = "kWh",
        /// `kvar`.
        Kvar = "kvar",
        /// `kvarh`.
        Kvarh = "kvarh",
        /// `var`.
        Var = "var",
        /// `varh`.
        Varh = "varh",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `UnlockStatus` enumeration.
    UnlockStatus {
        /// `Unlocked`.
        Unlocked = "Unlocked",
        /// `UnlockFailed`.
        UnlockFailed = "UnlockFailed",
        /// `NotSupported`.
        NotSupported = "NotSupported",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `UpdateFirmwareStatus` enumeration.
    UpdateFirmwareStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `AcceptedCanceled`.
        AcceptedCanceled = "AcceptedCanceled",
        /// `InvalidCertificate`.
        InvalidCertificate = "InvalidCertificate",
        /// `RevokedCertificate`.
        RevokedCertificate = "RevokedCertificate",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `UpdateStatus` enumeration.
    UpdateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
        /// `NotSupported`.
        NotSupported = "NotSupported",
        /// `VersionMismatch`.
        VersionMismatch = "VersionMismatch",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `UpdateType` enumeration.
    UpdateType {
        /// `Differential`.
        Differential = "Differential",
        /// `Full`.
        Full = "Full",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `UploadLogStatus` enumeration.
    UploadLogStatus {
        /// `BadMessage`.
        BadMessage = "BadMessage",
        /// `Idle`.
        Idle = "Idle",
        /// `NotSupportedOperation`.
        NotSupportedOperation = "NotSupportedOperation",
        /// `PermissionDenied`.
        PermissionDenied = "PermissionDenied",
        /// `Uploaded`.
        Uploaded = "Uploaded",
        /// `UploadFailure`.
        UploadFailure = "UploadFailure",
        /// `Uploading`.
        Uploading = "Uploading",
    }
}

ocpp_enum! {
    /// The OCPP 1.6 `ValueFormat` enumeration.
    ValueFormat {
        /// `Raw`.
        Raw = "Raw",
        /// `SignedData`.
        SignedData = "SignedData",
    }
}
