// @generated by `cargo xtask appendix` from OCPP 2.1 Part 2 — Appendices v2.0 (2025-01-23).
//
// Only the interoperability surface is reproduced: names, data types and criticality. The
// appendix's prose descriptions are not copied, and the appendix itself is not redistributed.
// DO NOT EDIT — re-run the generator instead.

//! The standardized components and variables of the OCPP 2.x device model.
//!
//! Appendix chapter 3 lists the component names two implementations are expected to
//! agree on, and the variables typically associated with each. Chapter 4 gives the
//! data type and unit of the variables that are not specific to one controller; those
//! are filled in here where the appendix leaves the type column empty.
//!
//! The list does not imply that a Charging Station must implement any of it. It is a
//! vocabulary, not a requirement — which is why
//! [`DeviceModel`](crate::station::device_model::DeviceModel) takes what it needs from
//! here rather than starting from all of it.

/// Whether a component is one of the logical `…Ctrlr` components or a physical one.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ComponentKind {
    /// A logical controller: `OCPPCommCtrlr`, `SecurityCtrlr`, `TxCtrlr`, …
    Controller,
    /// A physical part of the station: `EVSE`, `Connector`, `PowerContactor`, …
    Physical,
}

/// One variable the appendix associates with a component.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StandardVariable {
    /// The variable name.
    pub name: &'static str,
    /// The variable instance, written `Name[Instance]` in the appendix.
    pub instance: Option<&'static str>,
    /// The attribute, written `Name(Attribute)` — `MaxLimit`, `MinSet`, …
    pub attribute: Option<&'static str>,
    /// The `DataEnumType`, where the appendix gives one.
    pub data_type: Option<&'static str>,
    /// The unit, for the variables chapter 4 gives one for.
    pub unit: Option<&'static str>,
}

/// One standardized component.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StandardComponent {
    /// The component name.
    pub name: &'static str,
    /// Logical or physical.
    pub kind: ComponentKind,
    /// The variables typically associated with it.
    pub variables: &'static [StandardVariable],
}

static ALIGNEDDATACTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Available",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Interval",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "Measurands",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "SendDuringIdle",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "SignReadings",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "TxEndedInterval",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "TxEndedMeasurands",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
];

static AUTHCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "AdditionalInfoItemsPerMessage",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "AuthorizeRemoteStart",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "DisableRemoteAuthorization",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "LocalAuthorizeOffline",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "LocalPreAuthorize",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "MasterPassGroupId",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "OfflineTxForUnknownIdEnabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static AUTHCACHECTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Available",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "LifeTime",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "Policy",
        instance: None,
        attribute: None,
        data_type: Some("OptionList"),
        unit: None,
    },
    StandardVariable {
        name: "DisablePostAuthorize",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static CHADEMOCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Complete",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "SelftestActive",
        instance: None,
        attribute: Some("Set"),
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "SelftestActive",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Specific",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "CHAdeMOProtocolNumber",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "VehicleStatus",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "DynamicControl",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "HighCurrentControl",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "HighVoltageControl",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "AutoManufacturerCode",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
];

static CLOCKCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "DateTime",
        instance: None,
        attribute: None,
        data_type: Some("dateTime"),
        unit: None,
    },
    StandardVariable {
        name: "NtpServerUri",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "NtpSource",
        instance: None,
        attribute: None,
        data_type: Some("OptionList"),
        unit: None,
    },
    StandardVariable {
        name: "TimeOffset",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "NextTimeOffsetTransitionDateTime",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "TimeSource",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "TimeZone",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "TimeAdjustmentReportingThreshold",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
];

static CUSTOMIZATIONCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "CustomImplementationEnabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "CustomTriggers",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
];

static DEVICEDATACTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "BytesPerMessage",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "ItemsPerMessage",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "ValueSize",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
];

static DISPLAYMESSAGECTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Available",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "DisplayMessages",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "PersonalMessageSize",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "SupportedFormats",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "SupportedPriorities",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "SupportedStates",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "Language",
        instance: None,
        attribute: None,
        data_type: Some("OptionList"),
        unit: None,
    },
];

static ISO15118CTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Complete",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "SeccId",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "SelftestActive",
        instance: None,
        attribute: Some("Set"),
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "SelftestActive",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "ContractValidationOffline",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "CentralContractValidationAllowed",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "PnCEnabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "V2GCertificateInstallationEnabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "ContractCertificateInstallationEnabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "RequestMeteringReceipt",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "OrganizationName",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "CountryName",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Specific",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "MaxScheduleEntries",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "RequestedEnergyTransferMode",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
];

static LOCALAUTHLISTCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Entries",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "Available",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "ItemsPerMessage",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "BytesPerMessage",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "Storage",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("B"),
    },
    StandardVariable {
        name: "DisablePostAuthorize",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "SupportsExpiryDateTime",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static MONITORINGCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Available",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "ItemsPerMessage",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "BytesPerMessage",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "MonitoringBase",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "MonitoringLevel",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "OfflineQueuingSeverity",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "ActiveMonitoringBase",
        instance: None,
        attribute: None,
        data_type: Some("OptionList"),
        unit: None,
    },
    StandardVariable {
        name: "ActiveMonitoringLevel",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
];

static OCPPCOMMCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "ActiveNetworkProfile",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "FileTransferProtocols",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "HeartbeatInterval",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "MessageAttempts",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "MessageAttemptInterval",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "MessageTimeout",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "MinimumStatusDuration",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "NetworkConfigurationPriority",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "NetworkProfileConnectionAttempts",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "OfflineThreshold",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "PublicKeyWithSignedMeterValue",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "QueueAllMessages",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "RetryBackOffRepeatTimes",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "RetryBackOffRandomRange",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "RetryBackOffWaitMinimum",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "UnlockOnEVSideDisconnect",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "WebSocketPingInterval",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "FieldLength",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
];

static WEBPAYMENTSCTRLR: &[StandardVariable] = &[];

static RESERVATIONCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Available",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "NonEvseSpecific",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static SAMPLEDDATACTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Available",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "SignReadings",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "TxEndedMeasurands",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "TxEndedInterval",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "TxStartedMeasurands",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "TxUpdatedMeasurands",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "TxUpdatedInterval",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "RegisterValuesWithoutPhases",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static SECURITYCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "BasicAuthPassword",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Identity",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "OrganizationName",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "CertSigningWaitMinimum",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "CertSigningRepeatTimes",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "AllowSecurityProfileDowngrade",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static SMARTCHARGINGCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Available",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "ACPhaseSwitchingSupported",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "ProfileStackLevel",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "RateUnit",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "PeriodsPerSchedule",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "ExternalControlSignalsEnabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "NotifyChargingLimitWithSchedules",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Phases3to1",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Entries",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "LimitChangeSignificance",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
];

static TARIFFCOSTCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Available",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "TariffFallbackMessage",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "TotalCostFallbackMessage",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Currency",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static TXCTRLR: &[StandardVariable] = &[
    StandardVariable {
        name: "EVConnectionTimeOut",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "TxBeforeAcceptedEnabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "TxStartPoint",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "TxStopPoint",
        instance: None,
        attribute: None,
        data_type: Some("MemberList"),
        unit: None,
    },
    StandardVariable {
        name: "MaxEnergyOnInvalidId",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: Some("Wh"),
    },
    StandardVariable {
        name: "StopTxOnInvalidId",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "StopTxOnEVSideDisconnect",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static ACCESSBARRIER: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static ACDCCONVERTER: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Overload",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "DCVoltage",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("V"),
    },
    StandardVariable {
        name: "DCCurrent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("A"),
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "Temperature",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Celsius,"),
    },
    StandardVariable {
        name: "FanSpeed",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("RPM"),
    },
];

static ACPHASESELECTOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "PhaseRotation",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static ACTUATOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "State",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static AIRCOOLINGSYSTEM: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "FanSpeed",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("RPM"),
    },
];

static AREAVENTILATION: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "FanSpeed",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("RPM"),
    },
];

static BAYOCCUPANCYSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Percent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Percent"),
    },
];

static BEACONLIGHTING: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Percent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Percent"),
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "Color",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static CABLEBREAKAWAYSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static CASEACCESSSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static CHARGINGSTATION: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Overload",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "SupplyPhases",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "SupplyPhases",
        instance: None,
        attribute: Some("MaxLimit"),
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "PhaseRotation",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "ACVoltage",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("V"),
    },
    StandardVariable {
        name: "ACVoltage",
        instance: None,
        attribute: Some("MaxLimit"),
        data_type: Some("decimal"),
        unit: Some("V"),
    },
    StandardVariable {
        name: "ACCurrent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("A"),
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: Some("MaxLimit"),
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "VoltageImbalance",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Percent"),
    },
    StandardVariable {
        name: "CurrentImbalance",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Percent"),
    },
    StandardVariable {
        name: "VendorName",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "Model",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "ECVariant",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "SerialNumber",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "OperatingTimes",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "ChargeProtocol",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "AvailabilityState",
        instance: None,
        attribute: None,
        data_type: Some("OptionList"),
        unit: None,
    },
    StandardVariable {
        name: "AllowNewSessionsPendingFirmware",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "Update",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
];

static CHARGINGSTATUSINDICATOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Color",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static CONNECTEDEV: &[StandardVariable] = &[];

static CONNECTOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "ConnectorType",
        instance: None,
        attribute: None,
        data_type: Some("OptionList"),
        unit: None,
    },
    StandardVariable {
        name: "SupplyPhases",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "SupplyPhases",
        instance: None,
        attribute: Some("MaxLimit"),
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "PhaseRotation",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "ChargeProtocol",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "AvailabilityState",
        instance: None,
        attribute: None,
        data_type: Some("OptionList"),
        unit: None,
    },
];

static CONNECTORHOLSTERRELEASE: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "State",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static CONNECTORHOLSTERSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static CONNECTORPLUGRETENTIONLOCK: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tries",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "Tries",
        instance: None,
        attribute: Some("SetLimit"),
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "Tries",
        instance: None,
        attribute: Some("MaxLimit"),
        data_type: Some("integer"),
        unit: None,
    },
];

static CONNECTORPROTECTIONRELEASE: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static CONTROLLER: &[StandardVariable] = &[
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Interval",
        instance: Some("Heartbeat"),
        attribute: None,
        data_type: Some("integer"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "Manufacturer",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Model",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "ECVariant",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "SerialNumber",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "VersionNumber",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "VersionDate",
        instance: None,
        attribute: None,
        data_type: Some("dateTime"),
        unit: None,
    },
    StandardVariable {
        name: "FirmwareVersion",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "MaxMsgElements",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "SelftestActive",
        instance: None,
        attribute: Some("Set"),
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "SelftestActive",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
];

static CONTROLMETERING: &[StandardVariable] = &[
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "ACCurrent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("A"),
    },
    StandardVariable {
        name: "DCCurrent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("A"),
    },
    StandardVariable {
        name: "DCVoltage",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("V"),
    },
];

static CPPWMCONTROLLER: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "DCVoltage",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("V"),
    },
    StandardVariable {
        name: "State",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Percentage",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "SelftestActive",
        instance: None,
        attribute: Some("Set"),
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "SelftestActive",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
];

static DATALINK: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Fallback",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Complete",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "IMSI",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "ICCID",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "NetworkAddress",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "SignalStrength",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("dBm"),
    },
];

static DISPLAY: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Color",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Count",
        instance: Some("HeightInChars"),
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "Count",
        instance: Some("WidthInChars"),
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "DataText",
        instance: Some("Visible"),
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "State",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static ELECTRICALFEED: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "PowerType",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "Energy",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Wh"),
    },
    StandardVariable {
        name: "DCVoltage",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("V"),
    },
    StandardVariable {
        name: "SupplyPhases",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "PhaseRotation",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "ACVoltage",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("V"),
    },
];

static ELVSUPPLY: &[StandardVariable] = &[
    StandardVariable {
        name: "EnergyImportRegister",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Wh"),
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: Some("MaxLimit"),
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "Fallback",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "StateOfCharge",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Percent"),
    },
    StandardVariable {
        name: "Time",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
];

static EMERGENCYSTOPSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static ENVIRONMENTALLIGHTING: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Percent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Percent"),
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "Color",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static EVRETENTIONLOCK: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Complete",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static EVSE: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Overload",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "SupplyPhases",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "PhaseRotation",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "AllowReset",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "ACVoltage",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("V"),
    },
    StandardVariable {
        name: "ACCurrent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("A"),
    },
    StandardVariable {
        name: "DCVoltage",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("V"),
    },
    StandardVariable {
        name: "DCCurrent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("A"),
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "VoltageImbalance",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Percent"),
    },
    StandardVariable {
        name: "CurrentImbalance",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Percent"),
    },
    StandardVariable {
        name: "ChargeProtocol",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "ChargingTime",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "PostChargingTime",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("s"),
    },
    StandardVariable {
        name: "Count",
        instance: Some("ChargingProfiles"),
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "Count",
        instance: Some("ChargingProfiles"),
        attribute: Some("MaxLimit"),
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "ISO15118EvseId",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static EXTERNALTEMPERATURESENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Temperature",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Celsius,"),
    },
];

static FISCALMETERING: &[StandardVariable] = &[
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "EnergyImport",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Wh"),
    },
    StandardVariable {
        name: "EnergyImportRegister",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Wh"),
    },
    StandardVariable {
        name: "EnergyExport",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Wh"),
    },
    StandardVariable {
        name: "EnergyExportRegister",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Wh"),
    },
    StandardVariable {
        name: "Manufacturer",
        instance: Some("Meter"),
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Manufacturer",
        instance: Some("CT"),
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Model",
        instance: Some("Meter"),
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Model",
        instance: Some("CT"),
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "ECVariant",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "SerialNumber",
        instance: Some("Meter"),
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "SerialNumber",
        instance: Some("CT"),
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Certificate",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "OptionsSet",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
    StandardVariable {
        name: "OptionsSet",
        instance: None,
        attribute: None,
        data_type: None,
        unit: None,
    },
];

static FLOODSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Height",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("m"),
    },
    StandardVariable {
        name: "Percent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Percent"),
    },
];

static GROUNDISOLATIONPROTECTION: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Complete",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Impedance",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Ohm"),
    },
];

static HEATER: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: Some("MaxLimit"),
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "Power",
        instance: None,
        attribute: Some("MaxSet"),
        data_type: Some("decimal"),
        unit: Some("W,kW"),
    },
    StandardVariable {
        name: "Temperature",
        instance: None,
        attribute: Some("MinSet"),
        data_type: Some("decimal"),
        unit: Some("Celsius,"),
    },
    StandardVariable {
        name: "Temperature",
        instance: None,
        attribute: Some("MaxSet"),
        data_type: Some("decimal"),
        unit: Some("Celsius,"),
    },
];

static HUMIDITYSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Humidity",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("RH"),
    },
];

static LIGHTSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Light",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("lx"),
    },
];

static LIQUIDCOOLINGSYSTEM: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Temperature",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Celsius,"),
    },
];

static LOCALAVAILABILITYSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static LOCALCONTROLLER: &[StandardVariable] = &[];

static LOCALENERGYSTORAGE: &[StandardVariable] = &[
    StandardVariable {
        name: "EnergyCapacity",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Wh"),
    },
    StandardVariable {
        name: "Identity",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static OVERCURRENTPROTECTION: &[StandardVariable] = &[
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Operated",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "ACCurrent",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("A"),
    },
];

static OVERCURRENTPROTECTIONRECLOSER: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: Some("Set"),
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Complete",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Mode",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "Tries",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "Tries",
        instance: None,
        attribute: Some("SetLimit"),
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "Tries",
        instance: None,
        attribute: Some("MaxLimit"),
        data_type: Some("integer"),
        unit: None,
    },
];

static POWERCONTACTOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static RCD: &[StandardVariable] = &[
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Operated",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static RCDRECLOSER: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: Some("Set"),
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Complete",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tries",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "Tries",
        instance: None,
        attribute: Some("SetLimit"),
        data_type: Some("integer"),
        unit: None,
    },
    StandardVariable {
        name: "Tries",
        instance: None,
        attribute: Some("MaxLimit"),
        data_type: Some("integer"),
        unit: None,
    },
];

static REALTIMECLOCK: &[StandardVariable] = &[
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "DCVoltage",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("V"),
    },
    StandardVariable {
        name: "Fallback",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Fallback",
        instance: None,
        attribute: Some("MaxLimit"),
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static SHOCKSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Force",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("N"),
    },
];

static SPACESCOUNTSIGNAGE: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Count",
        instance: None,
        attribute: None,
        data_type: Some("integer"),
        unit: None,
    },
];

static SWITCH: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "State",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
];

static TEMPERATURESENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Temperature",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Celsius,"),
    },
];

static TILTSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Angle",
        instance: None,
        attribute: None,
        data_type: Some("decimal"),
        unit: Some("Deg"),
    },
];

static TOKENREADER: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Operated",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Token",
        instance: None,
        attribute: None,
        data_type: Some("string"),
        unit: None,
    },
    StandardVariable {
        name: "TokenType",
        instance: None,
        attribute: None,
        data_type: Some("OptionList"),
        unit: None,
    },
];

static UPSTREAMPROTECTIONTRIGGER: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: Some("Set"),
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Tripped",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Problem",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static UIINPUT: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Operated",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

static VEHICLEIDSENSOR: &[StandardVariable] = &[
    StandardVariable {
        name: "Enabled",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
    StandardVariable {
        name: "Active",
        instance: None,
        attribute: None,
        data_type: Some("boolean"),
        unit: None,
    },
];

/// Every standardized component, in appendix order.
pub static COMPONENTS: &[StandardComponent] = &[
    StandardComponent {
        name: "AlignedDataCtrlr",
        kind: ComponentKind::Controller,
        variables: ALIGNEDDATACTRLR,
    },
    StandardComponent {
        name: "AuthCtrlr",
        kind: ComponentKind::Controller,
        variables: AUTHCTRLR,
    },
    StandardComponent {
        name: "AuthCacheCtrlr",
        kind: ComponentKind::Controller,
        variables: AUTHCACHECTRLR,
    },
    StandardComponent {
        name: "CHAdeMOCtrlr",
        kind: ComponentKind::Controller,
        variables: CHADEMOCTRLR,
    },
    StandardComponent {
        name: "ClockCtrlr",
        kind: ComponentKind::Controller,
        variables: CLOCKCTRLR,
    },
    StandardComponent {
        name: "CustomizationCtrlr",
        kind: ComponentKind::Controller,
        variables: CUSTOMIZATIONCTRLR,
    },
    StandardComponent {
        name: "DeviceDataCtrlr",
        kind: ComponentKind::Controller,
        variables: DEVICEDATACTRLR,
    },
    StandardComponent {
        name: "DisplayMessageCtrlr",
        kind: ComponentKind::Controller,
        variables: DISPLAYMESSAGECTRLR,
    },
    StandardComponent {
        name: "ISO15118Ctrlr",
        kind: ComponentKind::Controller,
        variables: ISO15118CTRLR,
    },
    StandardComponent {
        name: "LocalAuthListCtrlr",
        kind: ComponentKind::Controller,
        variables: LOCALAUTHLISTCTRLR,
    },
    StandardComponent {
        name: "MonitoringCtrlr",
        kind: ComponentKind::Controller,
        variables: MONITORINGCTRLR,
    },
    StandardComponent {
        name: "OCPPCommCtrlr",
        kind: ComponentKind::Controller,
        variables: OCPPCOMMCTRLR,
    },
    StandardComponent {
        name: "WebPaymentsCtrlr",
        kind: ComponentKind::Controller,
        variables: WEBPAYMENTSCTRLR,
    },
    StandardComponent {
        name: "ReservationCtrlr",
        kind: ComponentKind::Controller,
        variables: RESERVATIONCTRLR,
    },
    StandardComponent {
        name: "SampledDataCtrlr",
        kind: ComponentKind::Controller,
        variables: SAMPLEDDATACTRLR,
    },
    StandardComponent {
        name: "SecurityCtrlr",
        kind: ComponentKind::Controller,
        variables: SECURITYCTRLR,
    },
    StandardComponent {
        name: "SmartChargingCtrlr",
        kind: ComponentKind::Controller,
        variables: SMARTCHARGINGCTRLR,
    },
    StandardComponent {
        name: "TariffCostCtrlr",
        kind: ComponentKind::Controller,
        variables: TARIFFCOSTCTRLR,
    },
    StandardComponent {
        name: "TxCtrlr",
        kind: ComponentKind::Controller,
        variables: TXCTRLR,
    },
    StandardComponent {
        name: "AccessBarrier",
        kind: ComponentKind::Physical,
        variables: ACCESSBARRIER,
    },
    StandardComponent {
        name: "AcDcConverter",
        kind: ComponentKind::Physical,
        variables: ACDCCONVERTER,
    },
    StandardComponent {
        name: "AcPhaseSelector",
        kind: ComponentKind::Physical,
        variables: ACPHASESELECTOR,
    },
    StandardComponent {
        name: "Actuator",
        kind: ComponentKind::Physical,
        variables: ACTUATOR,
    },
    StandardComponent {
        name: "AirCoolingSystem",
        kind: ComponentKind::Physical,
        variables: AIRCOOLINGSYSTEM,
    },
    StandardComponent {
        name: "AreaVentilation",
        kind: ComponentKind::Physical,
        variables: AREAVENTILATION,
    },
    StandardComponent {
        name: "BayOccupancySensor",
        kind: ComponentKind::Physical,
        variables: BAYOCCUPANCYSENSOR,
    },
    StandardComponent {
        name: "BeaconLighting",
        kind: ComponentKind::Physical,
        variables: BEACONLIGHTING,
    },
    StandardComponent {
        name: "CableBreakawaySensor",
        kind: ComponentKind::Physical,
        variables: CABLEBREAKAWAYSENSOR,
    },
    StandardComponent {
        name: "CaseAccessSensor",
        kind: ComponentKind::Physical,
        variables: CASEACCESSSENSOR,
    },
    StandardComponent {
        name: "ChargingStation",
        kind: ComponentKind::Physical,
        variables: CHARGINGSTATION,
    },
    StandardComponent {
        name: "ChargingStatusIndicator",
        kind: ComponentKind::Physical,
        variables: CHARGINGSTATUSINDICATOR,
    },
    StandardComponent {
        name: "ConnectedEV",
        kind: ComponentKind::Physical,
        variables: CONNECTEDEV,
    },
    StandardComponent {
        name: "Connector",
        kind: ComponentKind::Physical,
        variables: CONNECTOR,
    },
    StandardComponent {
        name: "ConnectorHolsterRelease",
        kind: ComponentKind::Physical,
        variables: CONNECTORHOLSTERRELEASE,
    },
    StandardComponent {
        name: "ConnectorHolsterSensor",
        kind: ComponentKind::Physical,
        variables: CONNECTORHOLSTERSENSOR,
    },
    StandardComponent {
        name: "ConnectorPlugRetentionLock",
        kind: ComponentKind::Physical,
        variables: CONNECTORPLUGRETENTIONLOCK,
    },
    StandardComponent {
        name: "ConnectorProtectionRelease",
        kind: ComponentKind::Physical,
        variables: CONNECTORPROTECTIONRELEASE,
    },
    StandardComponent {
        name: "Controller",
        kind: ComponentKind::Physical,
        variables: CONTROLLER,
    },
    StandardComponent {
        name: "ControlMetering",
        kind: ComponentKind::Physical,
        variables: CONTROLMETERING,
    },
    StandardComponent {
        name: "CPPWMController",
        kind: ComponentKind::Physical,
        variables: CPPWMCONTROLLER,
    },
    StandardComponent {
        name: "DataLink",
        kind: ComponentKind::Physical,
        variables: DATALINK,
    },
    StandardComponent {
        name: "Display",
        kind: ComponentKind::Physical,
        variables: DISPLAY,
    },
    StandardComponent {
        name: "ElectricalFeed",
        kind: ComponentKind::Physical,
        variables: ELECTRICALFEED,
    },
    StandardComponent {
        name: "ELVSupply",
        kind: ComponentKind::Physical,
        variables: ELVSUPPLY,
    },
    StandardComponent {
        name: "EmergencyStopSensor",
        kind: ComponentKind::Physical,
        variables: EMERGENCYSTOPSENSOR,
    },
    StandardComponent {
        name: "EnvironmentalLighting",
        kind: ComponentKind::Physical,
        variables: ENVIRONMENTALLIGHTING,
    },
    StandardComponent {
        name: "EVRetentionLock",
        kind: ComponentKind::Physical,
        variables: EVRETENTIONLOCK,
    },
    StandardComponent {
        name: "EVSE",
        kind: ComponentKind::Physical,
        variables: EVSE,
    },
    StandardComponent {
        name: "ExternalTemperatureSensor",
        kind: ComponentKind::Physical,
        variables: EXTERNALTEMPERATURESENSOR,
    },
    StandardComponent {
        name: "FiscalMetering",
        kind: ComponentKind::Physical,
        variables: FISCALMETERING,
    },
    StandardComponent {
        name: "FloodSensor",
        kind: ComponentKind::Physical,
        variables: FLOODSENSOR,
    },
    StandardComponent {
        name: "GroundIsolationProtection",
        kind: ComponentKind::Physical,
        variables: GROUNDISOLATIONPROTECTION,
    },
    StandardComponent {
        name: "Heater",
        kind: ComponentKind::Physical,
        variables: HEATER,
    },
    StandardComponent {
        name: "HumiditySensor",
        kind: ComponentKind::Physical,
        variables: HUMIDITYSENSOR,
    },
    StandardComponent {
        name: "LightSensor",
        kind: ComponentKind::Physical,
        variables: LIGHTSENSOR,
    },
    StandardComponent {
        name: "LiquidCoolingSystem",
        kind: ComponentKind::Physical,
        variables: LIQUIDCOOLINGSYSTEM,
    },
    StandardComponent {
        name: "LocalAvailabilitySensor",
        kind: ComponentKind::Physical,
        variables: LOCALAVAILABILITYSENSOR,
    },
    StandardComponent {
        name: "LocalController",
        kind: ComponentKind::Physical,
        variables: LOCALCONTROLLER,
    },
    StandardComponent {
        name: "LocalEnergyStorage",
        kind: ComponentKind::Physical,
        variables: LOCALENERGYSTORAGE,
    },
    StandardComponent {
        name: "OverCurrentProtection",
        kind: ComponentKind::Physical,
        variables: OVERCURRENTPROTECTION,
    },
    StandardComponent {
        name: "OverCurrentProtectionRecloser",
        kind: ComponentKind::Physical,
        variables: OVERCURRENTPROTECTIONRECLOSER,
    },
    StandardComponent {
        name: "PowerContactor",
        kind: ComponentKind::Physical,
        variables: POWERCONTACTOR,
    },
    StandardComponent {
        name: "RCD",
        kind: ComponentKind::Physical,
        variables: RCD,
    },
    StandardComponent {
        name: "RCDRecloser",
        kind: ComponentKind::Physical,
        variables: RCDRECLOSER,
    },
    StandardComponent {
        name: "RealTimeClock",
        kind: ComponentKind::Physical,
        variables: REALTIMECLOCK,
    },
    StandardComponent {
        name: "ShockSensor",
        kind: ComponentKind::Physical,
        variables: SHOCKSENSOR,
    },
    StandardComponent {
        name: "SpacesCountSignage",
        kind: ComponentKind::Physical,
        variables: SPACESCOUNTSIGNAGE,
    },
    StandardComponent {
        name: "Switch",
        kind: ComponentKind::Physical,
        variables: SWITCH,
    },
    StandardComponent {
        name: "TemperatureSensor",
        kind: ComponentKind::Physical,
        variables: TEMPERATURESENSOR,
    },
    StandardComponent {
        name: "TiltSensor",
        kind: ComponentKind::Physical,
        variables: TILTSENSOR,
    },
    StandardComponent {
        name: "TokenReader",
        kind: ComponentKind::Physical,
        variables: TOKENREADER,
    },
    StandardComponent {
        name: "UpstreamProtectionTrigger",
        kind: ComponentKind::Physical,
        variables: UPSTREAMPROTECTIONTRIGGER,
    },
    StandardComponent {
        name: "UIInput",
        kind: ComponentKind::Physical,
        variables: UIINPUT,
    },
    StandardComponent {
        name: "VehicleIdSensor",
        kind: ComponentKind::Physical,
        variables: VEHICLEIDSENSOR,
    },
];

/// Looks a component up by name.
#[must_use]
pub fn component(name: &str) -> Option<&'static StandardComponent> {
    COMPONENTS.iter().find(|component| component.name == name)
}

/// Looks a variable up within a component.
#[must_use]
pub fn variable(component: &str, name: &str) -> Option<&'static StandardVariable> {
    self::component(component)?
        .variables
        .iter()
        .find(|variable| variable.name == name)
}
