// @generated by `cargo xtask appendix` from OCPP 2.1 Part 2 — Appendices v2.0 (2025-01-23).
//
// Only the interoperability surface is reproduced: names, data types and criticality. The
// appendix's prose descriptions are not copied, and the appendix itself is not redistributed.
// DO NOT EDIT — re-run the generator instead.

//! The standardized `StatusInfo.reasonCode` values.
//!
//! Appendix chapter 5. `statusInfo` is optional and every message carries a status of
//! its own, so a reason code adds insight rather than meaning — but using the
//! standardized spelling is what lets the other side act on it automatically.

ocpp_enum! {
    /// A standardized reason code.
    ReasonCode {
        /// `BatteryDamaged`.
        BatteryDamaged = "BatteryDamaged",
        /// `BatterySoC`.
        BatterySoC = "BatterySoC",
        /// `BatterySoHLow`.
        BatterySoHLow = "BatterySoHLow",
        /// `BatteryType`.
        BatteryType = "BatteryType",
        /// `BatteryUnknown`.
        BatteryUnknown = "BatteryUnknown",
        /// `CSNotAccepted`.
        CSNotAccepted = "CSNotAccepted",
        /// `DuplicateProfile`.
        DuplicateProfile = "DuplicateProfile",
        /// `DuplicateRequestId`.
        DuplicateRequestId = "DuplicateRequestId",
        /// `FixedCable`.
        FixedCable = "FixedCable",
        /// `FwUpdateInProgress`.
        FwUpdateInProgress = "FwUpdateInProgress",
        /// `InternalError`.
        InternalError = "InternalError",
        /// `InvalidCSR`.
        InvalidCSR = "InvalidCSR",
        /// `InvalidCertificate`.
        InvalidCertificate = "InvalidCertificate",
        /// `InvalidIdToken`.
        InvalidIdToken = "InvalidIdToken",
        /// `InvalidMessageSeq`.
        InvalidMessageSeq = "InvalidMessageSeq",
        /// `InvalidProfile`.
        InvalidProfile = "InvalidProfile",
        /// `InvalidProfileId`.
        InvalidProfileId = "InvalidProfileId",
        /// `InvalidSchedule`.
        InvalidSchedule = "InvalidSchedule",
        /// `InvalidStackLevel`.
        InvalidStackLevel = "InvalidStackLevel",
        /// `InvalidURL`.
        InvalidURL = "InvalidURL",
        /// `InvalidValue`.
        InvalidValue = "InvalidValue",
        /// `MissingDevModelInfo`.
        MissingDevModelInfo = "MissingDevModelInfo",
        /// `MissingParam`.
        MissingParam = "MissingParam",
        /// `NoBatteryAvailable`.
        NoBatteryAvailable = "NoBatteryAvailable",
        /// `NoCable`.
        NoCable = "NoCable",
        /// `NoError`.
        NoError = "NoError",
        /// `NoFreqWattCurve`.
        NoFreqWattCurve = "NoFreqWattCurve",
        /// `NoPhaseForDC`.
        NoPhaseForDC = "NoPhaseForDC",
        /// `NoSignalWattCurve`.
        NoSignalWattCurve = "NoSignalWattCurve",
        /// `NotEnabled`.
        NotEnabled = "NotEnabled",
        /// `NotFound`.
        NotFound = "NotFound",
        /// `OutOfMemory`.
        OutOfMemory = "OutOfMemory",
        /// `OutOfStorage`.
        OutOfStorage = "OutOfStorage",
        /// `RateLimitExceeded`.
        RateLimitExceeded = "RateLimitExceeded",
        /// `ReadOnly`.
        ReadOnly = "ReadOnly",
        /// `RedirectNotAllowed`.
        RedirectNotAllowed = "RedirectNotAllowed",
        /// `TooLargeElement`.
        TooLargeElement = "TooLargeElement",
        /// `TooManyElements`.
        TooManyElements = "TooManyElements",
        /// `TxInProgress`.
        TxInProgress = "TxInProgress",
        /// `TxNotFound`.
        TxNotFound = "TxNotFound",
        /// `TxStarted`.
        TxStarted = "TxStarted",
        /// `UnknownConnectorId`.
        UnknownConnectorId = "UnknownConnectorId",
        /// `UnknownConnectorType`.
        UnknownConnectorType = "UnknownConnectorType",
        /// `UnknownEvse`.
        UnknownEvse = "UnknownEvse",
        /// `Unspecified`.
        Unspecified = "Unspecified",
        /// `UnsupportedKind`.
        UnsupportedKind = "UnsupportedKind",
        /// `UnsupportedParam`.
        UnsupportedParam = "UnsupportedParam",
        /// `UnsupportedPurpose`.
        UnsupportedPurpose = "UnsupportedPurpose",
        /// `UnsupportedRateUnit`.
        UnsupportedRateUnit = "UnsupportedRateUnit",
        /// `UnsupportedRequest`.
        UnsupportedRequest = "UnsupportedRequest",
        /// `ValueOutOfRange`.
        ValueOutOfRange = "ValueOutOfRange",
        /// `ValuePositiveOnly`.
        ValuePositiveOnly = "ValuePositiveOnly",
        /// `ValueTooHigh`.
        ValueTooHigh = "ValueTooHigh",
        /// `ValueTooLow`.
        ValueTooLow = "ValueTooLow",
        /// `ValueZeroNotAllowed`.
        ValueZeroNotAllowed = "ValueZeroNotAllowed",
        /// `WriteOnly`.
        WriteOnly = "WriteOnly",
    }
}
