// @generated by `cargo xtask codegen` from the vendored OCPP JSON schemas.
// DO NOT EDIT — re-run the generator instead. CI fails if this file is stale.

//! Enumerations defined by OCPP 2.1, generated from the official JSON schemas.

#![allow(unused_imports, clippy::doc_markdown, clippy::struct_excessive_bools)]
#![allow(
    clippy::too_many_lines,
    clippy::too_many_arguments,
    clippy::wildcard_imports
)]
#![allow(clippy::match_same_arms, clippy::fn_params_excessive_bools)]

use alloc::string::String;
use alloc::vec::Vec;

use crate::ocpp_enum;

ocpp_enum! {
    /// Authentication method.
    APNAuthentication {
        /// `PAP`.
        PAP = "PAP",
        /// `CHAP`.
        CHAP = "CHAP",
        /// `NONE`.
        NONE = "NONE",
        /// `AUTO`.
        AUTO = "AUTO",
    }
}

ocpp_enum! {
    /// Attribute type for which value is requested. When absent, default Actual is assumed.
    Attribute {
        /// `Actual`.
        Actual = "Actual",
        /// `Target`.
        Target = "Target",
        /// `MinSet`.
        MinSet = "MinSet",
        /// `MaxSet`.
        MaxSet = "MaxSet",
    }
}

impl Default for Attribute {
    /// Schema default: `Actual`.
    fn default() -> Self {
        Self::Actual
    }
}

ocpp_enum! {
    /// Current status of the ID Token.
    AuthorizationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Blocked`.
        Blocked = "Blocked",
        /// `ConcurrentTx`.
        ConcurrentTx = "ConcurrentTx",
        /// `Expired`.
        Expired = "Expired",
        /// `Invalid`.
        Invalid = "Invalid",
        /// `NoCredit`.
        NoCredit = "NoCredit",
        /// `NotAllowedTypeEVSE`.
        NotAllowedTypeEVSE = "NotAllowedTypeEVSE",
        /// `NotAtThisLocation`.
        NotAtThisLocation = "NotAtThisLocation",
        /// `NotAtThisTime`.
        NotAtThisTime = "NotAtThisTime",
        /// `Unknown`.
        Unknown = "Unknown",
    }
}

ocpp_enum! {
    /// Certificate status information.
    /// - if all certificates are valid: return 'Accepted'.
    /// - if one of the certificates was revoked, return 'CertificateRevoked'.
    AuthorizeCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `SignatureError`.
        SignatureError = "SignatureError",
        /// `CertificateExpired`.
        CertificateExpired = "CertificateExpired",
        /// `CertificateRevoked`.
        CertificateRevoked = "CertificateRevoked",
        /// `NoCertificateAvailable`.
        NoCertificateAvailable = "NoCertificateAvailable",
        /// `CertChainError`.
        CertChainError = "CertChainError",
        /// `ContractCancelled`.
        ContractCancelled = "ContractCancelled",
    }
}

ocpp_enum! {
    /// Battery in/out
    BatterySwapEvent {
        /// `BatteryIn`.
        BatteryIn = "BatteryIn",
        /// `BatteryOut`.
        BatteryOut = "BatteryOut",
        /// `BatteryOutTimeout`.
        BatteryOutTimeout = "BatteryOutTimeout",
    }
}

ocpp_enum! {
    /// This contains the reason for sending this message to the CSMS.
    BootReason {
        /// `ApplicationReset`.
        ApplicationReset = "ApplicationReset",
        /// `FirmwareUpdate`.
        FirmwareUpdate = "FirmwareUpdate",
        /// `LocalReset`.
        LocalReset = "LocalReset",
        /// `PowerUp`.
        PowerUp = "PowerUp",
        /// `RemoteReset`.
        RemoteReset = "RemoteReset",
        /// `ScheduledReset`.
        ScheduledReset = "ScheduledReset",
        /// `Triggered`.
        Triggered = "Triggered",
        /// `Unknown`.
        Unknown = "Unknown",
        /// `Watchdog`.
        Watchdog = "Watchdog",
    }
}

ocpp_enum! {
    /// This indicates the success or failure of the canceling of a reservation by CSMS.
    CancelReservationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Defines whether certificate needs to be installed or updated.
    CertificateAction {
        /// `Install`.
        Install = "Install",
        /// `Update`.
        Update = "Update",
    }
}

ocpp_enum! {
    /// Returns whether certificate signing has been accepted, otherwise rejected.
    CertificateSignedStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Indicates the type of the signed certificate that is returned. When omitted the certificate is used for both the 15118 connection (if implemented) and the Charging Station to CSMS connection. This field is required when a typeOfCertificate was included in the &lt;&lt;signcertificaterequest,SignCertificateRequest&gt;&gt; that requested this certificate to be signed AND both the 15118 connection and the Charging Station connection are implemented.
    CertificateSigningUse {
        /// `ChargingStationCertificate`.
        ChargingStationCertificate = "ChargingStationCertificate",
        /// `V2GCertificate`.
        V2GCertificate = "V2GCertificate",
        /// `V2G20Certificate`.
        V2G20Certificate = "V2G20Certificate",
    }
}

ocpp_enum! {
    /// Status of certificate: good, revoked or unknown.
    CertificateStatusEnum {
        /// `Good`.
        Good = "Good",
        /// `Revoked`.
        Revoked = "Revoked",
        /// `Unknown`.
        Unknown = "Unknown",
        /// `Failed`.
        Failed = "Failed",
    }
}

ocpp_enum! {
    /// Source of status: OCSP, CRL
    CertificateStatusSource {
        /// `CRL`.
        CRL = "CRL",
        /// `OCSP`.
        OCSP = "OCSP",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station is able to perform the availability change.
    ChangeAvailabilityStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Scheduled`.
        Scheduled = "Scheduled",
    }
}

ocpp_enum! {
    /// Indicates the kind of schedule.
    ChargingProfileKind {
        /// `Absolute`.
        Absolute = "Absolute",
        /// `Recurring`.
        Recurring = "Recurring",
        /// `Relative`.
        Relative = "Relative",
        /// `Dynamic`.
        Dynamic = "Dynamic",
    }
}

ocpp_enum! {
    /// Specifies to purpose of the charging profiles that will be cleared, if they meet the other criteria in the request.
    ChargingProfilePurpose {
        /// `ChargingStationExternalConstraints`.
        ChargingStationExternalConstraints = "ChargingStationExternalConstraints",
        /// `ChargingStationMaxProfile`.
        ChargingStationMaxProfile = "ChargingStationMaxProfile",
        /// `TxDefaultProfile`.
        TxDefaultProfile = "TxDefaultProfile",
        /// `TxProfile`.
        TxProfile = "TxProfile",
        /// `PriorityCharging`.
        PriorityCharging = "PriorityCharging",
        /// `LocalGeneration`.
        LocalGeneration = "LocalGeneration",
    }
}

ocpp_enum! {
    /// Result of request.
    ChargingProfileStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Can be used to force a power or current profile.
    ChargingRateUnit {
        /// `W`.
        W = "W",
        /// `A`.
        A = "A",
    }
}

ocpp_enum! {
    /// Current charging state, is required when state
    /// has changed. Omitted when there is no communication between EVSE and EV, because no cable is plugged in.
    ChargingState {
        /// `EVConnected`.
        EVConnected = "EVConnected",
        /// `Charging`.
        Charging = "Charging",
        /// `SuspendedEV`.
        SuspendedEV = "SuspendedEV",
        /// `SuspendedEVSE`.
        SuspendedEVSE = "SuspendedEVSE",
        /// `Idle`.
        Idle = "Idle",
    }
}

ocpp_enum! {
    /// Accepted if the Charging Station has executed the request, otherwise rejected.
    ClearCacheStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Indicates if the Charging Station was able to execute the request.
    ClearChargingProfileStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Unknown`.
        Unknown = "Unknown",
    }
}

ocpp_enum! {
    /// Returns whether the Charging Station has been able to remove the message.
    ClearMessageStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Unknown`.
        Unknown = "Unknown",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Result of the clear request for this monitor, identified by its Id.
    ClearMonitoringStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotFound`.
        NotFound = "NotFound",
    }
}

ocpp_enum! {
    /// The OCPP 2.1 `ComponentCriterion` enumeration.
    ComponentCriterion {
        /// `Active`.
        Active = "Active",
        /// `Available`.
        Available = "Available",
        /// `Enabled`.
        Enabled = "Enabled",
        /// `Problem`.
        Problem = "Problem",
    }
}

ocpp_enum! {
    /// This contains the current status of the Connector.
    ConnectorStatus {
        /// `Available`.
        Available = "Available",
        /// `Occupied`.
        Occupied = "Occupied",
        /// `Reserved`.
        Reserved = "Reserved",
        /// `Unavailable`.
        Unavailable = "Unavailable",
        /// `Faulted`.
        Faulted = "Faulted",
    }
}

ocpp_enum! {
    /// *(2.1)* Indicates whether EV wants to operate in Dynamic or Scheduled mode. When absent, Scheduled mode is assumed for backwards compatibility. +
    /// *ISO 15118-20:* +
    /// ServiceSelectionReq(SelectedEnergyTransferService)
    ControlMode {
        /// `ScheduledControl`.
        ScheduledControl = "ScheduledControl",
        /// `DynamicControl`.
        DynamicControl = "DynamicControl",
    }
}

ocpp_enum! {
    /// Type of cost dimension: energy, power, time, etc.
    CostDimensionEnum {
        /// `Energy`.
        Energy = "Energy",
        /// `MaxCurrent`.
        MaxCurrent = "MaxCurrent",
        /// `MinCurrent`.
        MinCurrent = "MinCurrent",
        /// `MaxPower`.
        MaxPower = "MaxPower",
        /// `MinPower`.
        MinPower = "MinPower",
        /// `IdleTIme`.
        IdleTIme = "IdleTIme",
        /// `ChargingTime`.
        ChargingTime = "ChargingTime",
    }
}

ocpp_enum! {
    /// The kind of cost referred to in the message element amount
    CostKind {
        /// `CarbonDioxideEmission`.
        CarbonDioxideEmission = "CarbonDioxideEmission",
        /// `RelativePricePercentage`.
        RelativePricePercentage = "RelativePricePercentage",
        /// `RenewableGenerationPercentage`.
        RenewableGenerationPercentage = "RenewableGenerationPercentage",
    }
}

ocpp_enum! {
    /// Indicates whether the request was accepted.
    CustomerInformationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Invalid`.
        Invalid = "Invalid",
    }
}

ocpp_enum! {
    /// Name of control settings to clear. Not used when _controlId_ is provided.
    DERControl {
        /// `EnterService`.
        EnterService = "EnterService",
        /// `FreqDroop`.
        FreqDroop = "FreqDroop",
        /// `FreqWatt`.
        FreqWatt = "FreqWatt",
        /// `FixedPFAbsorb`.
        FixedPFAbsorb = "FixedPFAbsorb",
        /// `FixedPFInject`.
        FixedPFInject = "FixedPFInject",
        /// `FixedVar`.
        FixedVar = "FixedVar",
        /// `Gradients`.
        Gradients = "Gradients",
        /// `HFMustTrip`.
        HFMustTrip = "HFMustTrip",
        /// `HFMayTrip`.
        HFMayTrip = "HFMayTrip",
        /// `HVMustTrip`.
        HVMustTrip = "HVMustTrip",
        /// `HVMomCess`.
        HVMomCess = "HVMomCess",
        /// `HVMayTrip`.
        HVMayTrip = "HVMayTrip",
        /// `LimitMaxDischarge`.
        LimitMaxDischarge = "LimitMaxDischarge",
        /// `LFMustTrip`.
        LFMustTrip = "LFMustTrip",
        /// `LVMustTrip`.
        LVMustTrip = "LVMustTrip",
        /// `LVMomCess`.
        LVMomCess = "LVMomCess",
        /// `LVMayTrip`.
        LVMayTrip = "LVMayTrip",
        /// `PowerMonitoringMustTrip`.
        PowerMonitoringMustTrip = "PowerMonitoringMustTrip",
        /// `VoltVar`.
        VoltVar = "VoltVar",
        /// `VoltWatt`.
        VoltWatt = "VoltWatt",
        /// `WattPF`.
        WattPF = "WattPF",
        /// `WattVar`.
        WattVar = "WattVar",
    }
}

ocpp_enum! {
    /// Result of operation.
    DERControlStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotSupported`.
        NotSupported = "NotSupported",
        /// `NotFound`.
        NotFound = "NotFound",
    }
}

ocpp_enum! {
    /// Unit of the Y-axis of DER curve
    DERUnit {
        /// `Not_Applicable`.
        NotApplicable = "Not_Applicable",
        /// `PctMaxW`.
        PctMaxW = "PctMaxW",
        /// `PctMaxVar`.
        PctMaxVar = "PctMaxVar",
        /// `PctWAvail`.
        PctWAvail = "PctWAvail",
        /// `PctVarAvail`.
        PctVarAvail = "PctVarAvail",
        /// `PctEffectiveV`.
        PctEffectiveV = "PctEffectiveV",
    }
}

ocpp_enum! {
    /// Data type of this variable.
    Data {
        /// `string`.
        String = "string",
        /// `decimal`.
        Decimal = "decimal",
        /// `integer`.
        Integer = "integer",
        /// `dateTime`.
        DateTime = "dateTime",
        /// `boolean`.
        Boolean = "boolean",
        /// `OptionList`.
        OptionList = "OptionList",
        /// `SequenceList`.
        SequenceList = "SequenceList",
        /// `MemberList`.
        MemberList = "MemberList",
    }
}

ocpp_enum! {
    /// This indicates the success or failure of the data transfer.
    DataTransferStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `UnknownMessageId`.
        UnknownMessageId = "UnknownMessageId",
        /// `UnknownVendorId`.
        UnknownVendorId = "UnknownVendorId",
    }
}

ocpp_enum! {
    /// The OCPP 2.1 `DayOfWeek` enumeration.
    DayOfWeek {
        /// `Monday`.
        Monday = "Monday",
        /// `Tuesday`.
        Tuesday = "Tuesday",
        /// `Wednesday`.
        Wednesday = "Wednesday",
        /// `Thursday`.
        Thursday = "Thursday",
        /// `Friday`.
        Friday = "Friday",
        /// `Saturday`.
        Saturday = "Saturday",
        /// `Sunday`.
        Sunday = "Sunday",
    }
}

ocpp_enum! {
    /// Charging Station indicates if it can process the request.
    DeleteCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
        /// `NotFound`.
        NotFound = "NotFound",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station is able to display the message.
    DisplayMessageStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `NotSupportedMessageFormat`.
        NotSupportedMessageFormat = "NotSupportedMessageFormat",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotSupportedPriority`.
        NotSupportedPriority = "NotSupportedPriority",
        /// `NotSupportedState`.
        NotSupportedState = "NotSupportedState",
        /// `UnknownTransaction`.
        UnknownTransaction = "UnknownTransaction",
        /// `LanguageNotSupported`.
        LanguageNotSupported = "LanguageNotSupported",
    }
}

ocpp_enum! {
    /// Mode of energy transfer requested by the EV.
    EnergyTransferMode {
        /// `AC_single_phase`.
        ACSinglePhase = "AC_single_phase",
        /// `AC_two_phase`.
        ACTwoPhase = "AC_two_phase",
        /// `AC_three_phase`.
        ACThreePhase = "AC_three_phase",
        /// `DC`.
        DC = "DC",
        /// `AC_BPT`.
        ACBPT = "AC_BPT",
        /// `AC_BPT_DER`.
        ACBPTDER = "AC_BPT_DER",
        /// `AC_DER`.
        ACDER = "AC_DER",
        /// `DC_BPT`.
        DCBPT = "DC_BPT",
        /// `DC_ACDP`.
        DCACDP = "DC_ACDP",
        /// `DC_ACDP_BPT`.
        DCACDPBPT = "DC_ACDP_BPT",
        /// `WPT`.
        WPT = "WPT",
    }
}

ocpp_enum! {
    /// Specifies the event notification type of the message.
    EventNotification {
        /// `HardWiredNotification`.
        HardWiredNotification = "HardWiredNotification",
        /// `HardWiredMonitor`.
        HardWiredMonitor = "HardWiredMonitor",
        /// `PreconfiguredMonitor`.
        PreconfiguredMonitor = "PreconfiguredMonitor",
        /// `CustomMonitor`.
        CustomMonitor = "CustomMonitor",
    }
}

ocpp_enum! {
    /// Type of trigger for this event, e.g. exceeding a threshold value.
    EventTrigger {
        /// `Alerting`.
        Alerting = "Alerting",
        /// `Delta`.
        Delta = "Delta",
        /// `Periodic`.
        Periodic = "Periodic",
    }
}

ocpp_enum! {
    /// Type of EVSE (AC, DC) this tariff applies to.
    EvseKind {
        /// `AC`.
        AC = "AC",
        /// `DC`.
        DC = "DC",
    }
}

ocpp_enum! {
    /// This contains the progress status of the firmware installation.
    FirmwareStatus {
        /// `Downloaded`.
        Downloaded = "Downloaded",
        /// `DownloadFailed`.
        DownloadFailed = "DownloadFailed",
        /// `Downloading`.
        Downloading = "Downloading",
        /// `DownloadScheduled`.
        DownloadScheduled = "DownloadScheduled",
        /// `DownloadPaused`.
        DownloadPaused = "DownloadPaused",
        /// `Idle`.
        Idle = "Idle",
        /// `InstallationFailed`.
        InstallationFailed = "InstallationFailed",
        /// `Installing`.
        Installing = "Installing",
        /// `Installed`.
        Installed = "Installed",
        /// `InstallRebooting`.
        InstallRebooting = "InstallRebooting",
        /// `InstallScheduled`.
        InstallScheduled = "InstallScheduled",
        /// `InstallVerificationFailed`.
        InstallVerificationFailed = "InstallVerificationFailed",
        /// `InvalidSignature`.
        InvalidSignature = "InvalidSignature",
        /// `SignatureVerified`.
        SignatureVerified = "SignatureVerified",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station is able to accept this request.
    GenericDeviceModelStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotSupported`.
        NotSupported = "NotSupported",
        /// `EmptyResultSet`.
        EmptyResultSet = "EmptyResultSet",
    }
}

ocpp_enum! {
    /// Status of operation.
    GenericStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Indicates the type of the requested certificate(s).
    GetCertificateIdUse {
        /// `V2GRootCertificate`.
        V2GRootCertificate = "V2GRootCertificate",
        /// `MORootCertificate`.
        MORootCertificate = "MORootCertificate",
        /// `CSMSRootCertificate`.
        CSMSRootCertificate = "CSMSRootCertificate",
        /// `V2GCertificateChain`.
        V2GCertificateChain = "V2GCertificateChain",
        /// `ManufacturerRootCertificate`.
        ManufacturerRootCertificate = "ManufacturerRootCertificate",
        /// `OEMRootCertificate`.
        OEMRootCertificate = "OEMRootCertificate",
    }
}

ocpp_enum! {
    /// This indicates whether the charging station was able to retrieve the OCSP certificate status.
    GetCertificateStatusEnum {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station is able to process this request and will send &lt;&lt;reportchargingprofilesrequest, ReportChargingProfilesRequest&gt;&gt; messages.
    GetChargingProfileStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `NoProfiles`.
        NoProfiles = "NoProfiles",
    }
}

ocpp_enum! {
    /// Indicates if the Charging Station has Display Messages that match the request criteria in the &lt;&lt;getdisplaymessagesrequest,GetDisplayMessagesRequest&gt;&gt;
    GetDisplayMessagesStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Unknown`.
        Unknown = "Unknown",
    }
}

ocpp_enum! {
    /// Charging Station indicates if it can process the request.
    GetInstalledCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `NotFound`.
        NotFound = "NotFound",
    }
}

ocpp_enum! {
    /// The OCPP 2.1 `GetVariableStatus` enumeration.
    GetVariableStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `UnknownComponent`.
        UnknownComponent = "UnknownComponent",
        /// `UnknownVariable`.
        UnknownVariable = "UnknownVariable",
        /// `NotSupportedAttributeType`.
        NotSupportedAttributeType = "NotSupportedAttributeType",
    }
}

ocpp_enum! {
    /// Type of grid event that caused this
    GridEventFault {
        /// `CurrentImbalance`.
        CurrentImbalance = "CurrentImbalance",
        /// `LocalEmergency`.
        LocalEmergency = "LocalEmergency",
        /// `LowInputPower`.
        LowInputPower = "LowInputPower",
        /// `OverCurrent`.
        OverCurrent = "OverCurrent",
        /// `OverFrequency`.
        OverFrequency = "OverFrequency",
        /// `OverVoltage`.
        OverVoltage = "OverVoltage",
        /// `PhaseRotation`.
        PhaseRotation = "PhaseRotation",
        /// `RemoteEmergency`.
        RemoteEmergency = "RemoteEmergency",
        /// `UnderFrequency`.
        UnderFrequency = "UnderFrequency",
        /// `UnderVoltage`.
        UnderVoltage = "UnderVoltage",
        /// `VoltageImbalance`.
        VoltageImbalance = "VoltageImbalance",
    }
}

ocpp_enum! {
    /// Used algorithms for the hashes provided.
    HashAlgorithm {
        /// `SHA256`.
        SHA256 = "SHA256",
        /// `SHA384`.
        SHA384 = "SHA384",
        /// `SHA512`.
        SHA512 = "SHA512",
    }
}

ocpp_enum! {
    /// Charging Station indicates if installation was successful.
    InstallCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Failed`.
        Failed = "Failed",
    }
}

ocpp_enum! {
    /// Indicates the certificate type that is sent.
    InstallCertificateUse {
        /// `V2GRootCertificate`.
        V2GRootCertificate = "V2GRootCertificate",
        /// `MORootCertificate`.
        MORootCertificate = "MORootCertificate",
        /// `ManufacturerRootCertificate`.
        ManufacturerRootCertificate = "ManufacturerRootCertificate",
        /// `CSMSRootCertificate`.
        CSMSRootCertificate = "CSMSRootCertificate",
        /// `OEMRootCertificate`.
        OEMRootCertificate = "OEMRootCertificate",
    }
}

ocpp_enum! {
    /// The OCPP 2.1 `IslandingDetection` enumeration.
    IslandingDetection {
        /// `NoAntiIslandingSupport`.
        NoAntiIslandingSupport = "NoAntiIslandingSupport",
        /// `RoCoF`.
        RoCoF = "RoCoF",
        /// `UVP_OVP`.
        UVPOVP = "UVP_OVP",
        /// `UFP_OFP`.
        UFPOFP = "UFP_OFP",
        /// `VoltageVectorShift`.
        VoltageVectorShift = "VoltageVectorShift",
        /// `ZeroCrossingDetection`.
        ZeroCrossingDetection = "ZeroCrossingDetection",
        /// `OtherPassive`.
        OtherPassive = "OtherPassive",
        /// `ImpedanceMeasurement`.
        ImpedanceMeasurement = "ImpedanceMeasurement",
        /// `ImpedanceAtFrequency`.
        ImpedanceAtFrequency = "ImpedanceAtFrequency",
        /// `SlipModeFrequencyShift`.
        SlipModeFrequencyShift = "SlipModeFrequencyShift",
        /// `SandiaFrequencyShift`.
        SandiaFrequencyShift = "SandiaFrequencyShift",
        /// `SandiaVoltageShift`.
        SandiaVoltageShift = "SandiaVoltageShift",
        /// `FrequencyJump`.
        FrequencyJump = "FrequencyJump",
        /// `RCLQFactor`.
        RCLQFactor = "RCLQFactor",
        /// `OtherActive`.
        OtherActive = "OtherActive",
    }
}

ocpp_enum! {
    /// Indicates whether the message was processed properly.
    Iso15118EVCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
    }
}

ocpp_enum! {
    /// Indicates where the measured value has been sampled. Default =  "Outlet"
    Location {
        /// `Body`.
        Body = "Body",
        /// `Cable`.
        Cable = "Cable",
        /// `EV`.
        EV = "EV",
        /// `Inlet`.
        Inlet = "Inlet",
        /// `Outlet`.
        Outlet = "Outlet",
        /// `Upstream`.
        Upstream = "Upstream",
    }
}

impl Default for Location {
    /// Schema default: `Outlet`.
    fn default() -> Self {
        Self::Outlet
    }
}

ocpp_enum! {
    /// This contains the type of log file that the Charging Station
    /// should send.
    Log {
        /// `DiagnosticsLog`.
        DiagnosticsLog = "DiagnosticsLog",
        /// `SecurityLog`.
        SecurityLog = "SecurityLog",
        /// `DataCollectorLog`.
        DataCollectorLog = "DataCollectorLog",
    }
}

ocpp_enum! {
    /// This field indicates whether the Charging Station was able to accept the request.
    LogStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `AcceptedCanceled`.
        AcceptedCanceled = "AcceptedCanceled",
    }
}

ocpp_enum! {
    /// Type of measurement. Default = "Energy.Active.Import.Register"
    Measurand {
        /// `Current.Export`.
        CurrentExport = "Current.Export",
        /// `Current.Export.Offered`.
        CurrentExportOffered = "Current.Export.Offered",
        /// `Current.Export.Minimum`.
        CurrentExportMinimum = "Current.Export.Minimum",
        /// `Current.Import`.
        CurrentImport = "Current.Import",
        /// `Current.Import.Offered`.
        CurrentImportOffered = "Current.Import.Offered",
        /// `Current.Import.Minimum`.
        CurrentImportMinimum = "Current.Import.Minimum",
        /// `Current.Offered`.
        CurrentOffered = "Current.Offered",
        /// `Display.PresentSOC`.
        DisplayPresentSOC = "Display.PresentSOC",
        /// `Display.MinimumSOC`.
        DisplayMinimumSOC = "Display.MinimumSOC",
        /// `Display.TargetSOC`.
        DisplayTargetSOC = "Display.TargetSOC",
        /// `Display.MaximumSOC`.
        DisplayMaximumSOC = "Display.MaximumSOC",
        /// `Display.RemainingTimeToMinimumSOC`.
        DisplayRemainingTimeToMinimumSOC = "Display.RemainingTimeToMinimumSOC",
        /// `Display.RemainingTimeToTargetSOC`.
        DisplayRemainingTimeToTargetSOC = "Display.RemainingTimeToTargetSOC",
        /// `Display.RemainingTimeToMaximumSOC`.
        DisplayRemainingTimeToMaximumSOC = "Display.RemainingTimeToMaximumSOC",
        /// `Display.ChargingComplete`.
        DisplayChargingComplete = "Display.ChargingComplete",
        /// `Display.BatteryEnergyCapacity`.
        DisplayBatteryEnergyCapacity = "Display.BatteryEnergyCapacity",
        /// `Display.InletHot`.
        DisplayInletHot = "Display.InletHot",
        /// `Energy.Active.Export.Interval`.
        EnergyActiveExportInterval = "Energy.Active.Export.Interval",
        /// `Energy.Active.Export.Register`.
        EnergyActiveExportRegister = "Energy.Active.Export.Register",
        /// `Energy.Active.Import.Interval`.
        EnergyActiveImportInterval = "Energy.Active.Import.Interval",
        /// `Energy.Active.Import.Register`.
        EnergyActiveImportRegister = "Energy.Active.Import.Register",
        /// `Energy.Active.Import.CableLoss`.
        EnergyActiveImportCableLoss = "Energy.Active.Import.CableLoss",
        /// `Energy.Active.Import.LocalGeneration.Register`.
        EnergyActiveImportLocalGenerationRegister = "Energy.Active.Import.LocalGeneration.Register",
        /// `Energy.Active.Net`.
        EnergyActiveNet = "Energy.Active.Net",
        /// `Energy.Active.Setpoint.Interval`.
        EnergyActiveSetpointInterval = "Energy.Active.Setpoint.Interval",
        /// `Energy.Apparent.Export`.
        EnergyApparentExport = "Energy.Apparent.Export",
        /// `Energy.Apparent.Import`.
        EnergyApparentImport = "Energy.Apparent.Import",
        /// `Energy.Apparent.Net`.
        EnergyApparentNet = "Energy.Apparent.Net",
        /// `Energy.Reactive.Export.Interval`.
        EnergyReactiveExportInterval = "Energy.Reactive.Export.Interval",
        /// `Energy.Reactive.Export.Register`.
        EnergyReactiveExportRegister = "Energy.Reactive.Export.Register",
        /// `Energy.Reactive.Import.Interval`.
        EnergyReactiveImportInterval = "Energy.Reactive.Import.Interval",
        /// `Energy.Reactive.Import.Register`.
        EnergyReactiveImportRegister = "Energy.Reactive.Import.Register",
        /// `Energy.Reactive.Net`.
        EnergyReactiveNet = "Energy.Reactive.Net",
        /// `EnergyRequest.Target`.
        EnergyRequestTarget = "EnergyRequest.Target",
        /// `EnergyRequest.Minimum`.
        EnergyRequestMinimum = "EnergyRequest.Minimum",
        /// `EnergyRequest.Maximum`.
        EnergyRequestMaximum = "EnergyRequest.Maximum",
        /// `EnergyRequest.Minimum.V2X`.
        EnergyRequestMinimumV2X = "EnergyRequest.Minimum.V2X",
        /// `EnergyRequest.Maximum.V2X`.
        EnergyRequestMaximumV2X = "EnergyRequest.Maximum.V2X",
        /// `EnergyRequest.Bulk`.
        EnergyRequestBulk = "EnergyRequest.Bulk",
        /// `Frequency`.
        Frequency = "Frequency",
        /// `Power.Active.Export`.
        PowerActiveExport = "Power.Active.Export",
        /// `Power.Active.Import`.
        PowerActiveImport = "Power.Active.Import",
        /// `Power.Active.Setpoint`.
        PowerActiveSetpoint = "Power.Active.Setpoint",
        /// `Power.Active.Residual`.
        PowerActiveResidual = "Power.Active.Residual",
        /// `Power.Export.Minimum`.
        PowerExportMinimum = "Power.Export.Minimum",
        /// `Power.Export.Offered`.
        PowerExportOffered = "Power.Export.Offered",
        /// `Power.Factor`.
        PowerFactor = "Power.Factor",
        /// `Power.Import.Offered`.
        PowerImportOffered = "Power.Import.Offered",
        /// `Power.Import.Minimum`.
        PowerImportMinimum = "Power.Import.Minimum",
        /// `Power.Offered`.
        PowerOffered = "Power.Offered",
        /// `Power.Reactive.Export`.
        PowerReactiveExport = "Power.Reactive.Export",
        /// `Power.Reactive.Import`.
        PowerReactiveImport = "Power.Reactive.Import",
        /// `SoC`.
        SoC = "SoC",
        /// `Voltage`.
        Voltage = "Voltage",
        /// `Voltage.Minimum`.
        VoltageMinimum = "Voltage.Minimum",
        /// `Voltage.Maximum`.
        VoltageMaximum = "Voltage.Maximum",
    }
}

impl Default for Measurand {
    /// Schema default: `Energy.Active.Import.Register`.
    fn default() -> Self {
        Self::EnergyActiveImportRegister
    }
}

ocpp_enum! {
    /// Format of the message.
    MessageFormat {
        /// `ASCII`.
        ASCII = "ASCII",
        /// `HTML`.
        HTML = "HTML",
        /// `URI`.
        URI = "URI",
        /// `UTF8`.
        UTF8 = "UTF8",
        /// `QRCODE`.
        QRCODE = "QRCODE",
    }
}

ocpp_enum! {
    /// If provided the Charging Station shall return Display Messages with the given priority only.
    MessagePriority {
        /// `AlwaysFront`.
        AlwaysFront = "AlwaysFront",
        /// `InFront`.
        InFront = "InFront",
        /// `NormalCycle`.
        NormalCycle = "NormalCycle",
    }
}

ocpp_enum! {
    /// If provided the Charging Station shall return Display Messages with the given state only.
    MessageState {
        /// `Charging`.
        Charging = "Charging",
        /// `Faulted`.
        Faulted = "Faulted",
        /// `Idle`.
        Idle = "Idle",
        /// `Unavailable`.
        Unavailable = "Unavailable",
        /// `Suspended`.
        Suspended = "Suspended",
        /// `Discharging`.
        Discharging = "Discharging",
    }
}

ocpp_enum! {
    /// Type of message to be triggered.
    MessageTrigger {
        /// `BootNotification`.
        BootNotification = "BootNotification",
        /// `LogStatusNotification`.
        LogStatusNotification = "LogStatusNotification",
        /// `FirmwareStatusNotification`.
        FirmwareStatusNotification = "FirmwareStatusNotification",
        /// `Heartbeat`.
        Heartbeat = "Heartbeat",
        /// `MeterValues`.
        MeterValues = "MeterValues",
        /// `SignChargingStationCertificate`.
        SignChargingStationCertificate = "SignChargingStationCertificate",
        /// `SignV2GCertificate`.
        SignV2GCertificate = "SignV2GCertificate",
        /// `SignV2G20Certificate`.
        SignV2G20Certificate = "SignV2G20Certificate",
        /// `StatusNotification`.
        StatusNotification = "StatusNotification",
        /// `TransactionEvent`.
        TransactionEvent = "TransactionEvent",
        /// `SignCombinedCertificate`.
        SignCombinedCertificate = "SignCombinedCertificate",
        /// `PublishFirmwareStatusNotification`.
        PublishFirmwareStatusNotification = "PublishFirmwareStatusNotification",
        /// `CustomTrigger`.
        CustomTrigger = "CustomTrigger",
    }
}

ocpp_enum! {
    /// *(2.1)* Value of EVCC indicates that EV determines min/target SOC and departure time. +
    /// A value of EVCC_SECC indicates that charging station or CSMS may also update min/target SOC and departure time. +
    /// *ISO 15118-20:* +
    /// ServiceSelectionReq(SelectedEnergyTransferService)
    MobilityNeedsMode {
        /// `EVCC`.
        EVCC = "EVCC",
        /// `EVCC_SECC`.
        EVCCSECC = "EVCC_SECC",
    }
}

ocpp_enum! {
    /// The type of this monitor, e.g. a threshold, delta or periodic monitor.
    Monitor {
        /// `UpperThreshold`.
        UpperThreshold = "UpperThreshold",
        /// `LowerThreshold`.
        LowerThreshold = "LowerThreshold",
        /// `Delta`.
        Delta = "Delta",
        /// `Periodic`.
        Periodic = "Periodic",
        /// `PeriodicClockAligned`.
        PeriodicClockAligned = "PeriodicClockAligned",
        /// `TargetDelta`.
        TargetDelta = "TargetDelta",
        /// `TargetDeltaRelative`.
        TargetDeltaRelative = "TargetDeltaRelative",
    }
}

ocpp_enum! {
    /// Specify which monitoring base will be set
    MonitoringBase {
        /// `All`.
        All = "All",
        /// `FactoryDefault`.
        FactoryDefault = "FactoryDefault",
        /// `HardWiredOnly`.
        HardWiredOnly = "HardWiredOnly",
    }
}

ocpp_enum! {
    /// The OCPP 2.1 `MonitoringCriterion` enumeration.
    MonitoringCriterion {
        /// `ThresholdMonitoring`.
        ThresholdMonitoring = "ThresholdMonitoring",
        /// `DeltaMonitoring`.
        DeltaMonitoring = "DeltaMonitoring",
        /// `PeriodicMonitoring`.
        PeriodicMonitoring = "PeriodicMonitoring",
    }
}

ocpp_enum! {
    /// Defines the mutability of this attribute. Default is ReadWrite when omitted.
    Mutability {
        /// `ReadOnly`.
        ReadOnly = "ReadOnly",
        /// `WriteOnly`.
        WriteOnly = "WriteOnly",
        /// `ReadWrite`.
        ReadWrite = "ReadWrite",
    }
}

impl Default for Mutability {
    /// Schema default: `ReadWrite`.
    fn default() -> Self {
        Self::ReadWrite
    }
}

ocpp_enum! {
    /// The OCPP 2.1 `NotifyAllowedEnergyTransferStatus` enumeration.
    NotifyAllowedEnergyTransferStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Returns whether the CSMS has been able to process the message successfully. It does not imply that the evChargingNeeds can be met with the current charging profile.
    NotifyEVChargingNeedsStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Processing`.
        Processing = "Processing",
        /// `NoChargingProfile`.
        NoChargingProfile = "NoChargingProfile",
    }
}

ocpp_enum! {
    /// Applicable Network Interface. Charging Station is allowed to use a different network interface to connect if the given one does not work.
    OCPPInterface {
        /// `Wired0`.
        Wired0 = "Wired0",
        /// `Wired1`.
        Wired1 = "Wired1",
        /// `Wired2`.
        Wired2 = "Wired2",
        /// `Wired3`.
        Wired3 = "Wired3",
        /// `Wireless0`.
        Wireless0 = "Wireless0",
        /// `Wireless1`.
        Wireless1 = "Wireless1",
        /// `Wireless2`.
        Wireless2 = "Wireless2",
        /// `Wireless3`.
        Wireless3 = "Wireless3",
        /// `Any`.
        Any = "Any",
    }
}

ocpp_enum! {
    /// Defines the transport protocol (e.g. SOAP or JSON). Note: SOAP is not supported in OCPP 2.x, but is supported by earlier versions of OCPP.
    OCPPTransport {
        /// `SOAP`.
        SOAP = "SOAP",
        /// `JSON`.
        JSON = "JSON",
    }
}

ocpp_enum! {
    /// *(2.1)* This field is ignored, since the OCPP version to use is determined during the websocket handshake. The field is only kept for backwards compatibility with the OCPP 2.0.1 JSON schema.
    OCPPVersion {
        /// `OCPP12`.
        OCPP12 = "OCPP12",
        /// `OCPP15`.
        OCPP15 = "OCPP15",
        /// `OCPP16`.
        OCPP16 = "OCPP16",
        /// `OCPP20`.
        OCPP20 = "OCPP20",
        /// `OCPP201`.
        OCPP201 = "OCPP201",
        /// `OCPP21`.
        OCPP21 = "OCPP21",
    }
}

ocpp_enum! {
    /// *(2.1)* Charging operation mode to use during this time interval. When absent defaults to `ChargingOnly`.
    OperationMode {
        /// `Idle`.
        Idle = "Idle",
        /// `ChargingOnly`.
        ChargingOnly = "ChargingOnly",
        /// `CentralSetpoint`.
        CentralSetpoint = "CentralSetpoint",
        /// `ExternalSetpoint`.
        ExternalSetpoint = "ExternalSetpoint",
        /// `ExternalLimits`.
        ExternalLimits = "ExternalLimits",
        /// `CentralFrequency`.
        CentralFrequency = "CentralFrequency",
        /// `LocalFrequency`.
        LocalFrequency = "LocalFrequency",
        /// `LocalLoadBalancing`.
        LocalLoadBalancing = "LocalLoadBalancing",
    }
}

ocpp_enum! {
    /// This contains the type of availability change that the Charging Station should perform.
    OperationalStatus {
        /// `Inoperative`.
        Inoperative = "Inoperative",
        /// `Operative`.
        Operative = "Operative",
    }
}

ocpp_enum! {
    /// The status of the settlement attempt.
    PaymentStatus {
        /// `Settled`.
        Settled = "Settled",
        /// `Canceled`.
        Canceled = "Canceled",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Failed`.
        Failed = "Failed",
    }
}

ocpp_enum! {
    /// Indicates how the measured value is to be interpreted. For instance between L1 and neutral (L1-N) Please note that not all values of phase are applicable to all Measurands. When phase is absent, the measured value is interpreted as an overall value.
    Phase {
        /// `L1`.
        L1 = "L1",
        /// `L2`.
        L2 = "L2",
        /// `L3`.
        L3 = "L3",
        /// `N`.
        N = "N",
        /// `L1-N`.
        L1N = "L1-N",
        /// `L2-N`.
        L2N = "L2-N",
        /// `L3-N`.
        L3N = "L3-N",
        /// `L1-L2`.
        L1L2 = "L1-L2",
        /// `L2-L3`.
        L2L3 = "L2-L3",
        /// `L3-L1`.
        L3L1 = "L3-L1",
    }
}

ocpp_enum! {
    /// Parameter is only sent, if the EV has to feed-in power or reactive power during fault-ride through (FRT) as defined by HVMomCess curve and LVMomCess curve.
    PowerDuringCessation {
        /// `Active`.
        Active = "Active",
        /// `Reactive`.
        Reactive = "Reactive",
    }
}

ocpp_enum! {
    /// *(2.1)* The current preconditioning status of the BMS in the EV. Default value is Unknown.
    PreconditioningStatus {
        /// `Unknown`.
        Unknown = "Unknown",
        /// `Ready`.
        Ready = "Ready",
        /// `NotReady`.
        NotReady = "NotReady",
        /// `Preconditioning`.
        Preconditioning = "Preconditioning",
    }
}

ocpp_enum! {
    /// Result of the request.
    PriorityChargingStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NoProfile`.
        NoProfile = "NoProfile",
    }
}

ocpp_enum! {
    /// This contains the progress status of the publishfirmware
    /// installation.
    PublishFirmwareStatus {
        /// `Idle`.
        Idle = "Idle",
        /// `DownloadScheduled`.
        DownloadScheduled = "DownloadScheduled",
        /// `Downloading`.
        Downloading = "Downloading",
        /// `Downloaded`.
        Downloaded = "Downloaded",
        /// `Published`.
        Published = "Published",
        /// `DownloadFailed`.
        DownloadFailed = "DownloadFailed",
        /// `DownloadPaused`.
        DownloadPaused = "DownloadPaused",
        /// `InvalidChecksum`.
        InvalidChecksum = "InvalidChecksum",
        /// `ChecksumVerified`.
        ChecksumVerified = "ChecksumVerified",
        /// `PublishFailed`.
        PublishFailed = "PublishFailed",
    }
}

ocpp_enum! {
    /// Type of detail value: start, end or sample. Default = "Sample.Periodic"
    ReadingContext {
        /// `Interruption.Begin`.
        InterruptionBegin = "Interruption.Begin",
        /// `Interruption.End`.
        InterruptionEnd = "Interruption.End",
        /// `Other`.
        Other = "Other",
        /// `Sample.Clock`.
        SampleClock = "Sample.Clock",
        /// `Sample.Periodic`.
        SamplePeriodic = "Sample.Periodic",
        /// `Transaction.Begin`.
        TransactionBegin = "Transaction.Begin",
        /// `Transaction.End`.
        TransactionEnd = "Transaction.End",
        /// `Trigger`.
        Trigger = "Trigger",
    }
}

impl Default for ReadingContext {
    /// Schema default: `Sample.Periodic`.
    fn default() -> Self {
        Self::SamplePeriodic
    }
}

ocpp_enum! {
    /// The _stoppedReason_ is the reason/event that initiated the process of stopping the transaction. It will normally be the user stopping authorization via card (Local or MasterPass) or app (Remote), but it can also be CSMS revoking authorization (DeAuthorized), or disconnecting the EV when TxStopPoint = EVConnected (EVDisconnected). Most other reasons are related to technical faults or energy limitations. +
    /// MAY only be omitted when _stoppedReason_ is "Local"
    Reason {
        /// `DeAuthorized`.
        DeAuthorized = "DeAuthorized",
        /// `EmergencyStop`.
        EmergencyStop = "EmergencyStop",
        /// `EnergyLimitReached`.
        EnergyLimitReached = "EnergyLimitReached",
        /// `EVDisconnected`.
        EVDisconnected = "EVDisconnected",
        /// `GroundFault`.
        GroundFault = "GroundFault",
        /// `ImmediateReset`.
        ImmediateReset = "ImmediateReset",
        /// `MasterPass`.
        MasterPass = "MasterPass",
        /// `Local`.
        Local = "Local",
        /// `LocalOutOfCredit`.
        LocalOutOfCredit = "LocalOutOfCredit",
        /// `Other`.
        Other = "Other",
        /// `OvercurrentFault`.
        OvercurrentFault = "OvercurrentFault",
        /// `PowerLoss`.
        PowerLoss = "PowerLoss",
        /// `PowerQuality`.
        PowerQuality = "PowerQuality",
        /// `Reboot`.
        Reboot = "Reboot",
        /// `Remote`.
        Remote = "Remote",
        /// `SOCLimitReached`.
        SOCLimitReached = "SOCLimitReached",
        /// `StoppedByEV`.
        StoppedByEV = "StoppedByEV",
        /// `TimeLimitReached`.
        TimeLimitReached = "TimeLimitReached",
        /// `Timeout`.
        Timeout = "Timeout",
        /// `ReqEnergyTransferRejected`.
        ReqEnergyTransferRejected = "ReqEnergyTransferRejected",
    }
}

ocpp_enum! {
    /// Indicates the start point of a recurrence.
    RecurrencyKind {
        /// `Daily`.
        Daily = "Daily",
        /// `Weekly`.
        Weekly = "Weekly",
    }
}

ocpp_enum! {
    /// This contains whether the Charging Station has been registered
    /// within the CSMS.
    RegistrationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Pending`.
        Pending = "Pending",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// This field specifies the report base.
    ReportBase {
        /// `ConfigurationInventory`.
        ConfigurationInventory = "ConfigurationInventory",
        /// `FullInventory`.
        FullInventory = "FullInventory",
        /// `SummaryInventory`.
        SummaryInventory = "SummaryInventory",
    }
}

ocpp_enum! {
    /// Status indicating whether the Charging Station accepts the request to start a transaction.
    RequestStartStopStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The updated reservation status.
    ReservationUpdateStatus {
        /// `Expired`.
        Expired = "Expired",
        /// `Removed`.
        Removed = "Removed",
        /// `NoTransaction`.
        NoTransaction = "NoTransaction",
    }
}

ocpp_enum! {
    /// This indicates the success or failure of the reservation.
    ReserveNowStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Faulted`.
        Faulted = "Faulted",
        /// `Occupied`.
        Occupied = "Occupied",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Unavailable`.
        Unavailable = "Unavailable",
    }
}

ocpp_enum! {
    /// This contains the type of reset that the Charging Station or EVSE should perform.
    ResetEnum {
        /// `Immediate`.
        Immediate = "Immediate",
        /// `OnIdle`.
        OnIdle = "OnIdle",
        /// `ImmediateAndResume`.
        ImmediateAndResume = "ImmediateAndResume",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station is able to perform the reset.
    ResetStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Scheduled`.
        Scheduled = "Scheduled",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station has successfully received and applied the update of the Local Authorization List.
    SendLocalListStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
        /// `VersionMismatch`.
        VersionMismatch = "VersionMismatch",
    }
}

ocpp_enum! {
    /// Status is OK if a value could be returned. Otherwise this will indicate the reason why a value could not be returned.
    SetMonitoringStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `UnknownComponent`.
        UnknownComponent = "UnknownComponent",
        /// `UnknownVariable`.
        UnknownVariable = "UnknownVariable",
        /// `UnsupportedMonitorType`.
        UnsupportedMonitorType = "UnsupportedMonitorType",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Duplicate`.
        Duplicate = "Duplicate",
    }
}

ocpp_enum! {
    /// Result of operation.
    SetNetworkProfileStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Failed`.
        Failed = "Failed",
    }
}

ocpp_enum! {
    /// Result status of setting the variable.
    SetVariableStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `UnknownComponent`.
        UnknownComponent = "UnknownComponent",
        /// `UnknownVariable`.
        UnknownVariable = "UnknownVariable",
        /// `NotSupportedAttributeType`.
        NotSupportedAttributeType = "NotSupportedAttributeType",
        /// `RebootRequired`.
        RebootRequired = "RebootRequired",
    }
}

ocpp_enum! {
    /// Status of the operation
    TariffChangeStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `TooManyElements`.
        TooManyElements = "TooManyElements",
        /// `ConditionNotSupported`.
        ConditionNotSupported = "ConditionNotSupported",
        /// `TxNotFound`.
        TxNotFound = "TxNotFound",
        /// `NoCurrencyChange`.
        NoCurrencyChange = "NoCurrencyChange",
    }
}

ocpp_enum! {
    /// The OCPP 2.1 `TariffClearStatus` enumeration.
    TariffClearStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NoTariff`.
        NoTariff = "NoTariff",
    }
}

ocpp_enum! {
    /// Type of cost: normal or the minimum or maximum cost.
    TariffCost {
        /// `NormalCost`.
        NormalCost = "NormalCost",
        /// `MinCost`.
        MinCost = "MinCost",
        /// `MaxCost`.
        MaxCost = "MaxCost",
    }
}

ocpp_enum! {
    /// Status of operation
    TariffGetStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NoTariff`.
        NoTariff = "NoTariff",
    }
}

ocpp_enum! {
    /// Kind of tariff (driver/default)
    TariffKind {
        /// `DefaultTariff`.
        DefaultTariff = "DefaultTariff",
        /// `DriverTariff`.
        DriverTariff = "DriverTariff",
    }
}

ocpp_enum! {
    /// The OCPP 2.1 `TariffSetStatus` enumeration.
    TariffSetStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `TooManyElements`.
        TooManyElements = "TooManyElements",
        /// `ConditionNotSupported`.
        ConditionNotSupported = "ConditionNotSupported",
        /// `DuplicateTariffId`.
        DuplicateTariffId = "DuplicateTariffId",
    }
}

ocpp_enum! {
    /// This contains the type of this event.
    /// The first TransactionEvent of a transaction SHALL contain: "Started" The last TransactionEvent of a transaction SHALL contain: "Ended" All others SHALL contain: "Updated"
    TransactionEventEnum {
        /// `Ended`.
        Ended = "Ended",
        /// `Started`.
        Started = "Started",
        /// `Updated`.
        Updated = "Updated",
    }
}

ocpp_enum! {
    /// Indicates whether the Charging Station will send the requested notification or not.
    TriggerMessageStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotImplemented`.
        NotImplemented = "NotImplemented",
    }
}

ocpp_enum! {
    /// Reason the Charging Station sends this message to the CSMS
    TriggerReason {
        /// `AbnormalCondition`.
        AbnormalCondition = "AbnormalCondition",
        /// `Authorized`.
        Authorized = "Authorized",
        /// `CablePluggedIn`.
        CablePluggedIn = "CablePluggedIn",
        /// `ChargingRateChanged`.
        ChargingRateChanged = "ChargingRateChanged",
        /// `ChargingStateChanged`.
        ChargingStateChanged = "ChargingStateChanged",
        /// `CostLimitReached`.
        CostLimitReached = "CostLimitReached",
        /// `Deauthorized`.
        Deauthorized = "Deauthorized",
        /// `EnergyLimitReached`.
        EnergyLimitReached = "EnergyLimitReached",
        /// `EVCommunicationLost`.
        EVCommunicationLost = "EVCommunicationLost",
        /// `EVConnectTimeout`.
        EVConnectTimeout = "EVConnectTimeout",
        /// `EVDeparted`.
        EVDeparted = "EVDeparted",
        /// `EVDetected`.
        EVDetected = "EVDetected",
        /// `LimitSet`.
        LimitSet = "LimitSet",
        /// `MeterValueClock`.
        MeterValueClock = "MeterValueClock",
        /// `MeterValuePeriodic`.
        MeterValuePeriodic = "MeterValuePeriodic",
        /// `OperationModeChanged`.
        OperationModeChanged = "OperationModeChanged",
        /// `RemoteStart`.
        RemoteStart = "RemoteStart",
        /// `RemoteStop`.
        RemoteStop = "RemoteStop",
        /// `ResetCommand`.
        ResetCommand = "ResetCommand",
        /// `RunningCost`.
        RunningCost = "RunningCost",
        /// `SignedDataReceived`.
        SignedDataReceived = "SignedDataReceived",
        /// `SoCLimitReached`.
        SoCLimitReached = "SoCLimitReached",
        /// `StopAuthorized`.
        StopAuthorized = "StopAuthorized",
        /// `TariffChanged`.
        TariffChanged = "TariffChanged",
        /// `TariffNotAccepted`.
        TariffNotAccepted = "TariffNotAccepted",
        /// `TimeLimitReached`.
        TimeLimitReached = "TimeLimitReached",
        /// `Trigger`.
        Trigger = "Trigger",
        /// `TxResumed`.
        TxResumed = "TxResumed",
        /// `UnlockCommand`.
        UnlockCommand = "UnlockCommand",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station has unlocked the connector.
    UnlockStatus {
        /// `Unlocked`.
        Unlocked = "Unlocked",
        /// `UnlockFailed`.
        UnlockFailed = "UnlockFailed",
        /// `OngoingAuthorizedTransaction`.
        OngoingAuthorizedTransaction = "OngoingAuthorizedTransaction",
        /// `UnknownConnector`.
        UnknownConnector = "UnknownConnector",
    }
}

ocpp_enum! {
    /// Indicates whether the Local Controller succeeded in unpublishing the firmware.
    UnpublishFirmwareStatus {
        /// `DownloadOngoing`.
        DownloadOngoing = "DownloadOngoing",
        /// `NoFirmware`.
        NoFirmware = "NoFirmware",
        /// `Unpublished`.
        Unpublished = "Unpublished",
    }
}

ocpp_enum! {
    /// This contains the type of update (full or differential) of this request.
    Update {
        /// `Differential`.
        Differential = "Differential",
        /// `Full`.
        Full = "Full",
    }
}

ocpp_enum! {
    /// This field indicates whether the Charging Station was able to accept the request.
    UpdateFirmwareStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `AcceptedCanceled`.
        AcceptedCanceled = "AcceptedCanceled",
        /// `InvalidCertificate`.
        InvalidCertificate = "InvalidCertificate",
        /// `RevokedCertificate`.
        RevokedCertificate = "RevokedCertificate",
    }
}

ocpp_enum! {
    /// This contains the status of the log upload.
    UploadLogStatus {
        /// `BadMessage`.
        BadMessage = "BadMessage",
        /// `Idle`.
        Idle = "Idle",
        /// `NotSupportedOperation`.
        NotSupportedOperation = "NotSupportedOperation",
        /// `PermissionDenied`.
        PermissionDenied = "PermissionDenied",
        /// `Uploaded`.
        Uploaded = "Uploaded",
        /// `UploadFailure`.
        UploadFailure = "UploadFailure",
        /// `Uploading`.
        Uploading = "Uploading",
        /// `AcceptedCanceled`.
        AcceptedCanceled = "AcceptedCanceled",
    }
}

ocpp_enum! {
    /// Type of VPN
    VPNEnum {
        /// `IKEv2`.
        IKEv2 = "IKEv2",
        /// `IPSec`.
        IPSec = "IPSec",
        /// `L2TP`.
        L2TP = "L2TP",
        /// `PPTP`.
        PPTP = "PPTP",
    }
}
