// @generated by `cargo xtask codegen` from the vendored OCPP JSON schemas.
// DO NOT EDIT — re-run the generator instead. CI fails if this file is stale.

//! OCPP 2.1 messages, generated from the official OCA JSON schemas.
//!
//! * 91 actions (38 originated by the Charging Station, 54 by the CSMS)
//! * [`Action`] names every action; [`CsRequest`] / [`CsmsRequest`] are the
//!   direction-aware unions the engine dispatches on.
//! * Every payload implements [`Validate`](crate::validate::Validate); the engine runs it
//!   after deserialization and maps failures to the right OCPP error code.

mod action;
mod enums;
mod messages;
mod types;

pub use action::{
    Action, CsRequest, CsResponse, CsmsRequest, CsmsResponse, transcode_request, transcode_response,
};
pub use enums::*;
pub use messages::*;
pub use types::*;
