// @generated by `cargo xtask codegen` from the vendored OCPP JSON schemas.
// DO NOT EDIT — re-run the generator instead. CI fails if this file is stale.

//! Enumerations defined by OCPP 2.0.1, generated from the official JSON schemas.

#![allow(unused_imports, clippy::doc_markdown, clippy::struct_excessive_bools)]
#![allow(
    clippy::too_many_lines,
    clippy::too_many_arguments,
    clippy::wildcard_imports
)]
#![allow(clippy::match_same_arms, clippy::fn_params_excessive_bools)]

use alloc::string::String;
use alloc::vec::Vec;

use crate::ocpp_enum;

ocpp_enum! {
    /// APN. APN_ Authentication. APN_ Authentication_ Code
    /// Authentication method.
    APNAuthentication {
        /// `CHAP`.
        CHAP = "CHAP",
        /// `NONE`.
        NONE = "NONE",
        /// `PAP`.
        PAP = "PAP",
        /// `AUTO`.
        AUTO = "AUTO",
    }
}

ocpp_enum! {
    /// Attribute type for which value is requested. When absent, default Actual is assumed.
    Attribute {
        /// `Actual`.
        Actual = "Actual",
        /// `Target`.
        Target = "Target",
        /// `MinSet`.
        MinSet = "MinSet",
        /// `MaxSet`.
        MaxSet = "MaxSet",
    }
}

impl Default for Attribute {
    /// Schema default: `Actual`.
    fn default() -> Self {
        Self::Actual
    }
}

ocpp_enum! {
    /// ID_ Token. Status. Authorization_ Status
    /// Current status of the ID Token.
    AuthorizationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Blocked`.
        Blocked = "Blocked",
        /// `ConcurrentTx`.
        ConcurrentTx = "ConcurrentTx",
        /// `Expired`.
        Expired = "Expired",
        /// `Invalid`.
        Invalid = "Invalid",
        /// `NoCredit`.
        NoCredit = "NoCredit",
        /// `NotAllowedTypeEVSE`.
        NotAllowedTypeEVSE = "NotAllowedTypeEVSE",
        /// `NotAtThisLocation`.
        NotAtThisLocation = "NotAtThisLocation",
        /// `NotAtThisTime`.
        NotAtThisTime = "NotAtThisTime",
        /// `Unknown`.
        Unknown = "Unknown",
    }
}

ocpp_enum! {
    /// Certificate status information.
    /// - if all certificates are valid: return 'Accepted'.
    /// - if one of the certificates was revoked, return 'CertificateRevoked'.
    AuthorizeCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `SignatureError`.
        SignatureError = "SignatureError",
        /// `CertificateExpired`.
        CertificateExpired = "CertificateExpired",
        /// `CertificateRevoked`.
        CertificateRevoked = "CertificateRevoked",
        /// `NoCertificateAvailable`.
        NoCertificateAvailable = "NoCertificateAvailable",
        /// `CertChainError`.
        CertChainError = "CertChainError",
        /// `ContractCancelled`.
        ContractCancelled = "ContractCancelled",
    }
}

ocpp_enum! {
    /// This contains the reason for sending this message to the CSMS.
    BootReason {
        /// `ApplicationReset`.
        ApplicationReset = "ApplicationReset",
        /// `FirmwareUpdate`.
        FirmwareUpdate = "FirmwareUpdate",
        /// `LocalReset`.
        LocalReset = "LocalReset",
        /// `PowerUp`.
        PowerUp = "PowerUp",
        /// `RemoteReset`.
        RemoteReset = "RemoteReset",
        /// `ScheduledReset`.
        ScheduledReset = "ScheduledReset",
        /// `Triggered`.
        Triggered = "Triggered",
        /// `Unknown`.
        Unknown = "Unknown",
        /// `Watchdog`.
        Watchdog = "Watchdog",
    }
}

ocpp_enum! {
    /// This indicates the success or failure of the canceling of a reservation by CSMS.
    CancelReservationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Defines whether certificate needs to be installed or updated.
    CertificateAction {
        /// `Install`.
        Install = "Install",
        /// `Update`.
        Update = "Update",
    }
}

ocpp_enum! {
    /// Returns whether certificate signing has been accepted, otherwise rejected.
    CertificateSignedStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Indicates the type of the signed certificate that is returned. When omitted the certificate is used for both the 15118 connection (if implemented) and the Charging Station to CSMS connection. This field is required when a typeOfCertificate was included in the &lt;&lt;signcertificaterequest,SignCertificateRequest&gt;&gt; that requested this certificate to be signed AND both the 15118 connection and the Charging Station connection are implemented.
    CertificateSigningUse {
        /// `ChargingStationCertificate`.
        ChargingStationCertificate = "ChargingStationCertificate",
        /// `V2GCertificate`.
        V2GCertificate = "V2GCertificate",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station is able to perform the availability change.
    ChangeAvailabilityStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Scheduled`.
        Scheduled = "Scheduled",
    }
}

ocpp_enum! {
    /// Source of the charging limit.
    ChargingLimitSource {
        /// `EMS`.
        EMS = "EMS",
        /// `Other`.
        Other = "Other",
        /// `SO`.
        SO = "SO",
        /// `CSO`.
        CSO = "CSO",
    }
}

ocpp_enum! {
    /// Charging_ Profile. Charging_ Profile_ Kind. Charging_ Profile_ Kind_ Code
    /// Indicates the kind of schedule.
    ChargingProfileKind {
        /// `Absolute`.
        Absolute = "Absolute",
        /// `Recurring`.
        Recurring = "Recurring",
        /// `Relative`.
        Relative = "Relative",
    }
}

ocpp_enum! {
    /// Charging_ Profile. Charging_ Profile_ Purpose. Charging_ Profile_ Purpose_ Code
    /// Specifies to purpose of the charging profiles that will be cleared, if they meet the other criteria in the request.
    ChargingProfilePurpose {
        /// `ChargingStationExternalConstraints`.
        ChargingStationExternalConstraints = "ChargingStationExternalConstraints",
        /// `ChargingStationMaxProfile`.
        ChargingStationMaxProfile = "ChargingStationMaxProfile",
        /// `TxDefaultProfile`.
        TxDefaultProfile = "TxDefaultProfile",
        /// `TxProfile`.
        TxProfile = "TxProfile",
    }
}

ocpp_enum! {
    /// Returns whether the Charging Station has been able to process the message successfully. This does not guarantee the schedule will be followed to the letter. There might be other constraints the Charging Station may need to take into account.
    ChargingProfileStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Can be used to force a power or current profile.
    ChargingRateUnit {
        /// `W`.
        W = "W",
        /// `A`.
        A = "A",
    }
}

ocpp_enum! {
    /// Transaction. State. Transaction_ State_ Code
    /// Current charging state, is required when state
    /// has changed.
    ChargingState {
        /// `Charging`.
        Charging = "Charging",
        /// `EVConnected`.
        EVConnected = "EVConnected",
        /// `SuspendedEV`.
        SuspendedEV = "SuspendedEV",
        /// `SuspendedEVSE`.
        SuspendedEVSE = "SuspendedEVSE",
        /// `Idle`.
        Idle = "Idle",
    }
}

ocpp_enum! {
    /// Accepted if the Charging Station has executed the request, otherwise rejected.
    ClearCacheStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Indicates if the Charging Station was able to execute the request.
    ClearChargingProfileStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Unknown`.
        Unknown = "Unknown",
    }
}

ocpp_enum! {
    /// Returns whether the Charging Station has been able to remove the message.
    ClearMessageStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Unknown`.
        Unknown = "Unknown",
    }
}

ocpp_enum! {
    /// Result of the clear request for this monitor, identified by its Id.
    ClearMonitoringStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotFound`.
        NotFound = "NotFound",
    }
}

ocpp_enum! {
    /// The OCPP 2.0.1 `ComponentCriterion` enumeration.
    ComponentCriterion {
        /// `Active`.
        Active = "Active",
        /// `Available`.
        Available = "Available",
        /// `Enabled`.
        Enabled = "Enabled",
        /// `Problem`.
        Problem = "Problem",
    }
}

ocpp_enum! {
    /// This field specifies the connector type.
    Connector {
        /// `cCCS1`.
        CCCS1 = "cCCS1",
        /// `cCCS2`.
        CCCS2 = "cCCS2",
        /// `cG105`.
        CG105 = "cG105",
        /// `cTesla`.
        CTesla = "cTesla",
        /// `cType1`.
        CType1 = "cType1",
        /// `cType2`.
        CType2 = "cType2",
        /// `s309-1P-16A`.
        S3091P16A = "s309-1P-16A",
        /// `s309-1P-32A`.
        S3091P32A = "s309-1P-32A",
        /// `s309-3P-16A`.
        S3093P16A = "s309-3P-16A",
        /// `s309-3P-32A`.
        S3093P32A = "s309-3P-32A",
        /// `sBS1361`.
        SBS1361 = "sBS1361",
        /// `sCEE-7-7`.
        SCEE77 = "sCEE-7-7",
        /// `sType2`.
        SType2 = "sType2",
        /// `sType3`.
        SType3 = "sType3",
        /// `Other1PhMax16A`.
        Other1PhMax16A = "Other1PhMax16A",
        /// `Other1PhOver16A`.
        Other1PhOver16A = "Other1PhOver16A",
        /// `Other3Ph`.
        Other3Ph = "Other3Ph",
        /// `Pan`.
        Pan = "Pan",
        /// `wInductive`.
        WInductive = "wInductive",
        /// `wResonant`.
        WResonant = "wResonant",
        /// `Undetermined`.
        Undetermined = "Undetermined",
        /// `Unknown`.
        Unknown = "Unknown",
    }
}

ocpp_enum! {
    /// This contains the current status of the Connector.
    ConnectorStatus {
        /// `Available`.
        Available = "Available",
        /// `Occupied`.
        Occupied = "Occupied",
        /// `Reserved`.
        Reserved = "Reserved",
        /// `Unavailable`.
        Unavailable = "Unavailable",
        /// `Faulted`.
        Faulted = "Faulted",
    }
}

ocpp_enum! {
    /// Cost. Cost_ Kind. Cost_ Kind_ Code
    /// The kind of cost referred to in the message element amount
    CostKind {
        /// `CarbonDioxideEmission`.
        CarbonDioxideEmission = "CarbonDioxideEmission",
        /// `RelativePricePercentage`.
        RelativePricePercentage = "RelativePricePercentage",
        /// `RenewableGenerationPercentage`.
        RenewableGenerationPercentage = "RenewableGenerationPercentage",
    }
}

ocpp_enum! {
    /// Indicates whether the request was accepted.
    CustomerInformationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Invalid`.
        Invalid = "Invalid",
    }
}

ocpp_enum! {
    /// Data type of this variable.
    Data {
        /// `string`.
        String = "string",
        /// `decimal`.
        Decimal = "decimal",
        /// `integer`.
        Integer = "integer",
        /// `dateTime`.
        DateTime = "dateTime",
        /// `boolean`.
        Boolean = "boolean",
        /// `OptionList`.
        OptionList = "OptionList",
        /// `SequenceList`.
        SequenceList = "SequenceList",
        /// `MemberList`.
        MemberList = "MemberList",
    }
}

ocpp_enum! {
    /// This indicates the success or failure of the data transfer.
    DataTransferStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `UnknownMessageId`.
        UnknownMessageId = "UnknownMessageId",
        /// `UnknownVendorId`.
        UnknownVendorId = "UnknownVendorId",
    }
}

ocpp_enum! {
    /// Charging Station indicates if it can process the request.
    DeleteCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
        /// `NotFound`.
        NotFound = "NotFound",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station is able to display the message.
    DisplayMessageStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `NotSupportedMessageFormat`.
        NotSupportedMessageFormat = "NotSupportedMessageFormat",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotSupportedPriority`.
        NotSupportedPriority = "NotSupportedPriority",
        /// `NotSupportedState`.
        NotSupportedState = "NotSupportedState",
        /// `UnknownTransaction`.
        UnknownTransaction = "UnknownTransaction",
    }
}

ocpp_enum! {
    /// Charging_ Needs. Requested. Energy_ Transfer_ Mode_ Code
    /// Mode of energy transfer requested by the EV.
    EnergyTransferMode {
        /// `DC`.
        DC = "DC",
        /// `AC_single_phase`.
        ACSinglePhase = "AC_single_phase",
        /// `AC_two_phase`.
        ACTwoPhase = "AC_two_phase",
        /// `AC_three_phase`.
        ACThreePhase = "AC_three_phase",
    }
}

ocpp_enum! {
    /// Specifies the event notification type of the message.
    EventNotification {
        /// `HardWiredNotification`.
        HardWiredNotification = "HardWiredNotification",
        /// `HardWiredMonitor`.
        HardWiredMonitor = "HardWiredMonitor",
        /// `PreconfiguredMonitor`.
        PreconfiguredMonitor = "PreconfiguredMonitor",
        /// `CustomMonitor`.
        CustomMonitor = "CustomMonitor",
    }
}

ocpp_enum! {
    /// Type of monitor that triggered this event, e.g. exceeding a threshold value.
    EventTrigger {
        /// `Alerting`.
        Alerting = "Alerting",
        /// `Delta`.
        Delta = "Delta",
        /// `Periodic`.
        Periodic = "Periodic",
    }
}

ocpp_enum! {
    /// This contains the progress status of the firmware installation.
    FirmwareStatus {
        /// `Downloaded`.
        Downloaded = "Downloaded",
        /// `DownloadFailed`.
        DownloadFailed = "DownloadFailed",
        /// `Downloading`.
        Downloading = "Downloading",
        /// `DownloadScheduled`.
        DownloadScheduled = "DownloadScheduled",
        /// `DownloadPaused`.
        DownloadPaused = "DownloadPaused",
        /// `Idle`.
        Idle = "Idle",
        /// `InstallationFailed`.
        InstallationFailed = "InstallationFailed",
        /// `Installing`.
        Installing = "Installing",
        /// `Installed`.
        Installed = "Installed",
        /// `InstallRebooting`.
        InstallRebooting = "InstallRebooting",
        /// `InstallScheduled`.
        InstallScheduled = "InstallScheduled",
        /// `InstallVerificationFailed`.
        InstallVerificationFailed = "InstallVerificationFailed",
        /// `InvalidSignature`.
        InvalidSignature = "InvalidSignature",
        /// `SignatureVerified`.
        SignatureVerified = "SignatureVerified",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station is able to accept this request.
    GenericDeviceModelStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotSupported`.
        NotSupported = "NotSupported",
        /// `EmptyResultSet`.
        EmptyResultSet = "EmptyResultSet",
    }
}

ocpp_enum! {
    /// The Charging Station will indicate if it was
    /// able to process the request
    GenericStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// Indicates the type of the requested certificate(s).
    GetCertificateIdUse {
        /// `V2GRootCertificate`.
        V2GRootCertificate = "V2GRootCertificate",
        /// `MORootCertificate`.
        MORootCertificate = "MORootCertificate",
        /// `CSMSRootCertificate`.
        CSMSRootCertificate = "CSMSRootCertificate",
        /// `V2GCertificateChain`.
        V2GCertificateChain = "V2GCertificateChain",
        /// `ManufacturerRootCertificate`.
        ManufacturerRootCertificate = "ManufacturerRootCertificate",
    }
}

ocpp_enum! {
    /// This indicates whether the charging station was able to retrieve the OCSP certificate status.
    GetCertificateStatusEnum {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station is able to process this request and will send &lt;&lt;reportchargingprofilesrequest, ReportChargingProfilesRequest&gt;&gt; messages.
    GetChargingProfileStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `NoProfiles`.
        NoProfiles = "NoProfiles",
    }
}

ocpp_enum! {
    /// Indicates if the Charging Station has Display Messages that match the request criteria in the &lt;&lt;getdisplaymessagesrequest,GetDisplayMessagesRequest&gt;&gt;
    GetDisplayMessagesStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Unknown`.
        Unknown = "Unknown",
    }
}

ocpp_enum! {
    /// Charging Station indicates if it can process the request.
    GetInstalledCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `NotFound`.
        NotFound = "NotFound",
    }
}

ocpp_enum! {
    /// Result status of getting the variable.
    GetVariableStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `UnknownComponent`.
        UnknownComponent = "UnknownComponent",
        /// `UnknownVariable`.
        UnknownVariable = "UnknownVariable",
        /// `NotSupportedAttributeType`.
        NotSupportedAttributeType = "NotSupportedAttributeType",
    }
}

ocpp_enum! {
    /// Used algorithms for the hashes provided.
    HashAlgorithm {
        /// `SHA256`.
        SHA256 = "SHA256",
        /// `SHA384`.
        SHA384 = "SHA384",
        /// `SHA512`.
        SHA512 = "SHA512",
    }
}

ocpp_enum! {
    /// Enumeration of possible idToken types.
    IdTokenEnum {
        /// `Central`.
        Central = "Central",
        /// `eMAID`.
        EMAID = "eMAID",
        /// `ISO14443`.
        ISO14443 = "ISO14443",
        /// `ISO15693`.
        ISO15693 = "ISO15693",
        /// `KeyCode`.
        KeyCode = "KeyCode",
        /// `Local`.
        Local = "Local",
        /// `MacAddress`.
        MacAddress = "MacAddress",
        /// `NoAuthorization`.
        NoAuthorization = "NoAuthorization",
    }
}

ocpp_enum! {
    /// Charging Station indicates if installation was successful.
    InstallCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Failed`.
        Failed = "Failed",
    }
}

ocpp_enum! {
    /// Indicates the certificate type that is sent.
    InstallCertificateUse {
        /// `V2GRootCertificate`.
        V2GRootCertificate = "V2GRootCertificate",
        /// `MORootCertificate`.
        MORootCertificate = "MORootCertificate",
        /// `CSMSRootCertificate`.
        CSMSRootCertificate = "CSMSRootCertificate",
        /// `ManufacturerRootCertificate`.
        ManufacturerRootCertificate = "ManufacturerRootCertificate",
    }
}

ocpp_enum! {
    /// Indicates whether the message was processed properly.
    Iso15118EVCertificateStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
    }
}

ocpp_enum! {
    /// Sampled_ Value. Location. Location_ Code
    /// Indicates where the measured value has been sampled. Default =  "Outlet"
    Location {
        /// `Body`.
        Body = "Body",
        /// `Cable`.
        Cable = "Cable",
        /// `EV`.
        EV = "EV",
        /// `Inlet`.
        Inlet = "Inlet",
        /// `Outlet`.
        Outlet = "Outlet",
    }
}

impl Default for Location {
    /// Schema default: `Outlet`.
    fn default() -> Self {
        Self::Outlet
    }
}

ocpp_enum! {
    /// This contains the type of log file that the Charging Station
    /// should send.
    Log {
        /// `DiagnosticsLog`.
        DiagnosticsLog = "DiagnosticsLog",
        /// `SecurityLog`.
        SecurityLog = "SecurityLog",
    }
}

ocpp_enum! {
    /// This field indicates whether the Charging Station was able to accept the request.
    LogStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `AcceptedCanceled`.
        AcceptedCanceled = "AcceptedCanceled",
    }
}

ocpp_enum! {
    /// Sampled_ Value. Measurand. Measurand_ Code
    /// Type of measurement. Default = "Energy.Active.Import.Register"
    Measurand {
        /// `Current.Export`.
        CurrentExport = "Current.Export",
        /// `Current.Import`.
        CurrentImport = "Current.Import",
        /// `Current.Offered`.
        CurrentOffered = "Current.Offered",
        /// `Energy.Active.Export.Register`.
        EnergyActiveExportRegister = "Energy.Active.Export.Register",
        /// `Energy.Active.Import.Register`.
        EnergyActiveImportRegister = "Energy.Active.Import.Register",
        /// `Energy.Reactive.Export.Register`.
        EnergyReactiveExportRegister = "Energy.Reactive.Export.Register",
        /// `Energy.Reactive.Import.Register`.
        EnergyReactiveImportRegister = "Energy.Reactive.Import.Register",
        /// `Energy.Active.Export.Interval`.
        EnergyActiveExportInterval = "Energy.Active.Export.Interval",
        /// `Energy.Active.Import.Interval`.
        EnergyActiveImportInterval = "Energy.Active.Import.Interval",
        /// `Energy.Active.Net`.
        EnergyActiveNet = "Energy.Active.Net",
        /// `Energy.Reactive.Export.Interval`.
        EnergyReactiveExportInterval = "Energy.Reactive.Export.Interval",
        /// `Energy.Reactive.Import.Interval`.
        EnergyReactiveImportInterval = "Energy.Reactive.Import.Interval",
        /// `Energy.Reactive.Net`.
        EnergyReactiveNet = "Energy.Reactive.Net",
        /// `Energy.Apparent.Net`.
        EnergyApparentNet = "Energy.Apparent.Net",
        /// `Energy.Apparent.Import`.
        EnergyApparentImport = "Energy.Apparent.Import",
        /// `Energy.Apparent.Export`.
        EnergyApparentExport = "Energy.Apparent.Export",
        /// `Frequency`.
        Frequency = "Frequency",
        /// `Power.Active.Export`.
        PowerActiveExport = "Power.Active.Export",
        /// `Power.Active.Import`.
        PowerActiveImport = "Power.Active.Import",
        /// `Power.Factor`.
        PowerFactor = "Power.Factor",
        /// `Power.Offered`.
        PowerOffered = "Power.Offered",
        /// `Power.Reactive.Export`.
        PowerReactiveExport = "Power.Reactive.Export",
        /// `Power.Reactive.Import`.
        PowerReactiveImport = "Power.Reactive.Import",
        /// `SoC`.
        SoC = "SoC",
        /// `Voltage`.
        Voltage = "Voltage",
    }
}

impl Default for Measurand {
    /// Schema default: `Energy.Active.Import.Register`.
    fn default() -> Self {
        Self::EnergyActiveImportRegister
    }
}

ocpp_enum! {
    /// Message_ Content. Format. Message_ Format_ Code
    /// urn:x-enexis:ecdm:uid:1:570848
    /// Format of the message.
    MessageFormat {
        /// `ASCII`.
        ASCII = "ASCII",
        /// `HTML`.
        HTML = "HTML",
        /// `URI`.
        URI = "URI",
        /// `UTF8`.
        UTF8 = "UTF8",
    }
}

ocpp_enum! {
    /// If provided the Charging Station shall return Display Messages with the given priority only.
    MessagePriority {
        /// `AlwaysFront`.
        AlwaysFront = "AlwaysFront",
        /// `InFront`.
        InFront = "InFront",
        /// `NormalCycle`.
        NormalCycle = "NormalCycle",
    }
}

ocpp_enum! {
    /// If provided the Charging Station shall return Display Messages with the given state only.
    MessageState {
        /// `Charging`.
        Charging = "Charging",
        /// `Faulted`.
        Faulted = "Faulted",
        /// `Idle`.
        Idle = "Idle",
        /// `Unavailable`.
        Unavailable = "Unavailable",
    }
}

ocpp_enum! {
    /// Type of message to be triggered.
    MessageTrigger {
        /// `BootNotification`.
        BootNotification = "BootNotification",
        /// `LogStatusNotification`.
        LogStatusNotification = "LogStatusNotification",
        /// `FirmwareStatusNotification`.
        FirmwareStatusNotification = "FirmwareStatusNotification",
        /// `Heartbeat`.
        Heartbeat = "Heartbeat",
        /// `MeterValues`.
        MeterValues = "MeterValues",
        /// `SignChargingStationCertificate`.
        SignChargingStationCertificate = "SignChargingStationCertificate",
        /// `SignV2GCertificate`.
        SignV2GCertificate = "SignV2GCertificate",
        /// `StatusNotification`.
        StatusNotification = "StatusNotification",
        /// `TransactionEvent`.
        TransactionEvent = "TransactionEvent",
        /// `SignCombinedCertificate`.
        SignCombinedCertificate = "SignCombinedCertificate",
        /// `PublishFirmwareStatusNotification`.
        PublishFirmwareStatusNotification = "PublishFirmwareStatusNotification",
    }
}

ocpp_enum! {
    /// The type of this monitor, e.g. a threshold, delta or periodic monitor.
    Monitor {
        /// `UpperThreshold`.
        UpperThreshold = "UpperThreshold",
        /// `LowerThreshold`.
        LowerThreshold = "LowerThreshold",
        /// `Delta`.
        Delta = "Delta",
        /// `Periodic`.
        Periodic = "Periodic",
        /// `PeriodicClockAligned`.
        PeriodicClockAligned = "PeriodicClockAligned",
    }
}

ocpp_enum! {
    /// Specify which monitoring base will be set
    MonitoringBase {
        /// `All`.
        All = "All",
        /// `FactoryDefault`.
        FactoryDefault = "FactoryDefault",
        /// `HardWiredOnly`.
        HardWiredOnly = "HardWiredOnly",
    }
}

ocpp_enum! {
    /// The OCPP 2.0.1 `MonitoringCriterion` enumeration.
    MonitoringCriterion {
        /// `ThresholdMonitoring`.
        ThresholdMonitoring = "ThresholdMonitoring",
        /// `DeltaMonitoring`.
        DeltaMonitoring = "DeltaMonitoring",
        /// `PeriodicMonitoring`.
        PeriodicMonitoring = "PeriodicMonitoring",
    }
}

ocpp_enum! {
    /// Defines the mutability of this attribute. Default is ReadWrite when omitted.
    Mutability {
        /// `ReadOnly`.
        ReadOnly = "ReadOnly",
        /// `WriteOnly`.
        WriteOnly = "WriteOnly",
        /// `ReadWrite`.
        ReadWrite = "ReadWrite",
    }
}

impl Default for Mutability {
    /// Schema default: `ReadWrite`.
    fn default() -> Self {
        Self::ReadWrite
    }
}

ocpp_enum! {
    /// Returns whether the CSMS has been able to process the message successfully. It does not imply that the evChargingNeeds can be met with the current charging profile.
    NotifyEVChargingNeedsStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Processing`.
        Processing = "Processing",
    }
}

ocpp_enum! {
    /// Applicable Network Interface.
    OCPPInterface {
        /// `Wired0`.
        Wired0 = "Wired0",
        /// `Wired1`.
        Wired1 = "Wired1",
        /// `Wired2`.
        Wired2 = "Wired2",
        /// `Wired3`.
        Wired3 = "Wired3",
        /// `Wireless0`.
        Wireless0 = "Wireless0",
        /// `Wireless1`.
        Wireless1 = "Wireless1",
        /// `Wireless2`.
        Wireless2 = "Wireless2",
        /// `Wireless3`.
        Wireless3 = "Wireless3",
    }
}

ocpp_enum! {
    /// Communication_ Function. OCPP_ Transport. OCPP_ Transport_ Code
    /// Defines the transport protocol (e.g. SOAP or JSON). Note: SOAP is not supported in OCPP 2.0, but is supported by other versions of OCPP.
    OCPPTransport {
        /// `JSON`.
        JSON = "JSON",
        /// `SOAP`.
        SOAP = "SOAP",
    }
}

ocpp_enum! {
    /// Communication_ Function. OCPP_ Version. OCPP_ Version_ Code
    /// Defines the OCPP version used for this communication function.
    OCPPVersion {
        /// `OCPP12`.
        OCPP12 = "OCPP12",
        /// `OCPP15`.
        OCPP15 = "OCPP15",
        /// `OCPP16`.
        OCPP16 = "OCPP16",
        /// `OCPP20`.
        OCPP20 = "OCPP20",
    }
}

ocpp_enum! {
    /// This contains the type of availability change that the Charging Station should perform.
    OperationalStatus {
        /// `Inoperative`.
        Inoperative = "Inoperative",
        /// `Operative`.
        Operative = "Operative",
    }
}

ocpp_enum! {
    /// Sampled_ Value. Phase. Phase_ Code
    /// Indicates how the measured value is to be interpreted. For instance between L1 and neutral (L1-N) Please note that not all values of phase are applicable to all Measurands. When phase is absent, the measured value is interpreted as an overall value.
    Phase {
        /// `L1`.
        L1 = "L1",
        /// `L2`.
        L2 = "L2",
        /// `L3`.
        L3 = "L3",
        /// `N`.
        N = "N",
        /// `L1-N`.
        L1N = "L1-N",
        /// `L2-N`.
        L2N = "L2-N",
        /// `L3-N`.
        L3N = "L3-N",
        /// `L1-L2`.
        L1L2 = "L1-L2",
        /// `L2-L3`.
        L2L3 = "L2-L3",
        /// `L3-L1`.
        L3L1 = "L3-L1",
    }
}

ocpp_enum! {
    /// This contains the progress status of the publishfirmware
    /// installation.
    PublishFirmwareStatus {
        /// `Idle`.
        Idle = "Idle",
        /// `DownloadScheduled`.
        DownloadScheduled = "DownloadScheduled",
        /// `Downloading`.
        Downloading = "Downloading",
        /// `Downloaded`.
        Downloaded = "Downloaded",
        /// `Published`.
        Published = "Published",
        /// `DownloadFailed`.
        DownloadFailed = "DownloadFailed",
        /// `DownloadPaused`.
        DownloadPaused = "DownloadPaused",
        /// `InvalidChecksum`.
        InvalidChecksum = "InvalidChecksum",
        /// `ChecksumVerified`.
        ChecksumVerified = "ChecksumVerified",
        /// `PublishFailed`.
        PublishFailed = "PublishFailed",
    }
}

ocpp_enum! {
    /// Sampled_ Value. Context. Reading_ Context_ Code
    /// Type of detail value: start, end or sample. Default = "Sample.Periodic"
    ReadingContext {
        /// `Interruption.Begin`.
        InterruptionBegin = "Interruption.Begin",
        /// `Interruption.End`.
        InterruptionEnd = "Interruption.End",
        /// `Other`.
        Other = "Other",
        /// `Sample.Clock`.
        SampleClock = "Sample.Clock",
        /// `Sample.Periodic`.
        SamplePeriodic = "Sample.Periodic",
        /// `Transaction.Begin`.
        TransactionBegin = "Transaction.Begin",
        /// `Transaction.End`.
        TransactionEnd = "Transaction.End",
        /// `Trigger`.
        Trigger = "Trigger",
    }
}

impl Default for ReadingContext {
    /// Schema default: `Sample.Periodic`.
    fn default() -> Self {
        Self::SamplePeriodic
    }
}

ocpp_enum! {
    /// Transaction. Stopped_ Reason. EOT_ Reason_ Code
    /// This contains the reason why the transaction was stopped. MAY only be omitted when Reason is "Local".
    Reason {
        /// `DeAuthorized`.
        DeAuthorized = "DeAuthorized",
        /// `EmergencyStop`.
        EmergencyStop = "EmergencyStop",
        /// `EnergyLimitReached`.
        EnergyLimitReached = "EnergyLimitReached",
        /// `EVDisconnected`.
        EVDisconnected = "EVDisconnected",
        /// `GroundFault`.
        GroundFault = "GroundFault",
        /// `ImmediateReset`.
        ImmediateReset = "ImmediateReset",
        /// `Local`.
        Local = "Local",
        /// `LocalOutOfCredit`.
        LocalOutOfCredit = "LocalOutOfCredit",
        /// `MasterPass`.
        MasterPass = "MasterPass",
        /// `Other`.
        Other = "Other",
        /// `OvercurrentFault`.
        OvercurrentFault = "OvercurrentFault",
        /// `PowerLoss`.
        PowerLoss = "PowerLoss",
        /// `PowerQuality`.
        PowerQuality = "PowerQuality",
        /// `Reboot`.
        Reboot = "Reboot",
        /// `Remote`.
        Remote = "Remote",
        /// `SOCLimitReached`.
        SOCLimitReached = "SOCLimitReached",
        /// `StoppedByEV`.
        StoppedByEV = "StoppedByEV",
        /// `TimeLimitReached`.
        TimeLimitReached = "TimeLimitReached",
        /// `Timeout`.
        Timeout = "Timeout",
    }
}

ocpp_enum! {
    /// Charging_ Profile. Recurrency_ Kind. Recurrency_ Kind_ Code
    /// Indicates the start point of a recurrence.
    RecurrencyKind {
        /// `Daily`.
        Daily = "Daily",
        /// `Weekly`.
        Weekly = "Weekly",
    }
}

ocpp_enum! {
    /// This contains whether the Charging Station has been registered
    /// within the CSMS.
    RegistrationStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Pending`.
        Pending = "Pending",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// This field specifies the report base.
    ReportBase {
        /// `ConfigurationInventory`.
        ConfigurationInventory = "ConfigurationInventory",
        /// `FullInventory`.
        FullInventory = "FullInventory",
        /// `SummaryInventory`.
        SummaryInventory = "SummaryInventory",
    }
}

ocpp_enum! {
    /// Status indicating whether the Charging Station accepts the request to start a transaction.
    RequestStartStopStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
    }
}

ocpp_enum! {
    /// The updated reservation status.
    ReservationUpdateStatus {
        /// `Expired`.
        Expired = "Expired",
        /// `Removed`.
        Removed = "Removed",
    }
}

ocpp_enum! {
    /// This indicates the success or failure of the reservation.
    ReserveNowStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Faulted`.
        Faulted = "Faulted",
        /// `Occupied`.
        Occupied = "Occupied",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Unavailable`.
        Unavailable = "Unavailable",
    }
}

ocpp_enum! {
    /// This contains the type of reset that the Charging Station or EVSE should perform.
    ResetEnum {
        /// `Immediate`.
        Immediate = "Immediate",
        /// `OnIdle`.
        OnIdle = "OnIdle",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station is able to perform the reset.
    ResetStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Scheduled`.
        Scheduled = "Scheduled",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station has successfully received and applied the update of the Local Authorization List.
    SendLocalListStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Failed`.
        Failed = "Failed",
        /// `VersionMismatch`.
        VersionMismatch = "VersionMismatch",
    }
}

ocpp_enum! {
    /// Status is OK if a value could be returned. Otherwise this will indicate the reason why a value could not be returned.
    SetMonitoringStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `UnknownComponent`.
        UnknownComponent = "UnknownComponent",
        /// `UnknownVariable`.
        UnknownVariable = "UnknownVariable",
        /// `UnsupportedMonitorType`.
        UnsupportedMonitorType = "UnsupportedMonitorType",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Duplicate`.
        Duplicate = "Duplicate",
    }
}

ocpp_enum! {
    /// Result of operation.
    SetNetworkProfileStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `Failed`.
        Failed = "Failed",
    }
}

ocpp_enum! {
    /// Result status of setting the variable.
    SetVariableStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `UnknownComponent`.
        UnknownComponent = "UnknownComponent",
        /// `UnknownVariable`.
        UnknownVariable = "UnknownVariable",
        /// `NotSupportedAttributeType`.
        NotSupportedAttributeType = "NotSupportedAttributeType",
        /// `RebootRequired`.
        RebootRequired = "RebootRequired",
    }
}

ocpp_enum! {
    /// This contains the type of this event.
    /// The first TransactionEvent of a transaction SHALL contain: "Started" The last TransactionEvent of a transaction SHALL contain: "Ended" All others SHALL contain: "Updated"
    TransactionEventEnum {
        /// `Ended`.
        Ended = "Ended",
        /// `Started`.
        Started = "Started",
        /// `Updated`.
        Updated = "Updated",
    }
}

ocpp_enum! {
    /// Indicates whether the Charging Station will send the requested notification or not.
    TriggerMessageStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `NotImplemented`.
        NotImplemented = "NotImplemented",
    }
}

ocpp_enum! {
    /// Reason the Charging Station sends this message to the CSMS
    TriggerReason {
        /// `Authorized`.
        Authorized = "Authorized",
        /// `CablePluggedIn`.
        CablePluggedIn = "CablePluggedIn",
        /// `ChargingRateChanged`.
        ChargingRateChanged = "ChargingRateChanged",
        /// `ChargingStateChanged`.
        ChargingStateChanged = "ChargingStateChanged",
        /// `Deauthorized`.
        Deauthorized = "Deauthorized",
        /// `EnergyLimitReached`.
        EnergyLimitReached = "EnergyLimitReached",
        /// `EVCommunicationLost`.
        EVCommunicationLost = "EVCommunicationLost",
        /// `EVConnectTimeout`.
        EVConnectTimeout = "EVConnectTimeout",
        /// `MeterValueClock`.
        MeterValueClock = "MeterValueClock",
        /// `MeterValuePeriodic`.
        MeterValuePeriodic = "MeterValuePeriodic",
        /// `TimeLimitReached`.
        TimeLimitReached = "TimeLimitReached",
        /// `Trigger`.
        Trigger = "Trigger",
        /// `UnlockCommand`.
        UnlockCommand = "UnlockCommand",
        /// `StopAuthorized`.
        StopAuthorized = "StopAuthorized",
        /// `EVDeparted`.
        EVDeparted = "EVDeparted",
        /// `EVDetected`.
        EVDetected = "EVDetected",
        /// `RemoteStop`.
        RemoteStop = "RemoteStop",
        /// `RemoteStart`.
        RemoteStart = "RemoteStart",
        /// `AbnormalCondition`.
        AbnormalCondition = "AbnormalCondition",
        /// `SignedDataReceived`.
        SignedDataReceived = "SignedDataReceived",
        /// `ResetCommand`.
        ResetCommand = "ResetCommand",
    }
}

ocpp_enum! {
    /// This indicates whether the Charging Station has unlocked the connector.
    UnlockStatus {
        /// `Unlocked`.
        Unlocked = "Unlocked",
        /// `UnlockFailed`.
        UnlockFailed = "UnlockFailed",
        /// `OngoingAuthorizedTransaction`.
        OngoingAuthorizedTransaction = "OngoingAuthorizedTransaction",
        /// `UnknownConnector`.
        UnknownConnector = "UnknownConnector",
    }
}

ocpp_enum! {
    /// Indicates whether the Local Controller succeeded in unpublishing the firmware.
    UnpublishFirmwareStatus {
        /// `DownloadOngoing`.
        DownloadOngoing = "DownloadOngoing",
        /// `NoFirmware`.
        NoFirmware = "NoFirmware",
        /// `Unpublished`.
        Unpublished = "Unpublished",
    }
}

ocpp_enum! {
    /// This contains the type of update (full or differential) of this request.
    Update {
        /// `Differential`.
        Differential = "Differential",
        /// `Full`.
        Full = "Full",
    }
}

ocpp_enum! {
    /// This field indicates whether the Charging Station was able to accept the request.
    UpdateFirmwareStatus {
        /// `Accepted`.
        Accepted = "Accepted",
        /// `Rejected`.
        Rejected = "Rejected",
        /// `AcceptedCanceled`.
        AcceptedCanceled = "AcceptedCanceled",
        /// `InvalidCertificate`.
        InvalidCertificate = "InvalidCertificate",
        /// `RevokedCertificate`.
        RevokedCertificate = "RevokedCertificate",
    }
}

ocpp_enum! {
    /// This contains the status of the log upload.
    UploadLogStatus {
        /// `BadMessage`.
        BadMessage = "BadMessage",
        /// `Idle`.
        Idle = "Idle",
        /// `NotSupportedOperation`.
        NotSupportedOperation = "NotSupportedOperation",
        /// `PermissionDenied`.
        PermissionDenied = "PermissionDenied",
        /// `Uploaded`.
        Uploaded = "Uploaded",
        /// `UploadFailure`.
        UploadFailure = "UploadFailure",
        /// `Uploading`.
        Uploading = "Uploading",
        /// `AcceptedCanceled`.
        AcceptedCanceled = "AcceptedCanceled",
    }
}

ocpp_enum! {
    /// VPN. Type. VPN_ Code
    /// Type of VPN
    VPNEnum {
        /// `IKEv2`.
        IKEv2 = "IKEv2",
        /// `IPSec`.
        IPSec = "IPSec",
        /// `L2TP`.
        L2TP = "L2TP",
        /// `PPTP`.
        PPTP = "PPTP",
    }
}
