//! Renders the IR to Rust source.

use std::fmt::Write as _;

use crate::model::{EnumDef, MessageDef, StructDef, Ty, Typed, VersionId, VersionModel};
use crate::naming::doc_lines;
use crate::registry::{Kind, Origin, block_name};

const HEADER: &str = "\
// @generated by `cargo xtask codegen` from the vendored OCPP JSON schemas.
// DO NOT EDIT — re-run the generator instead. CI fails if this file is stale.
";

fn preamble(module_doc: &str) -> String {
    format!(
        "{HEADER}\n\
         //! {module_doc}\n\
         \n\
         #![allow(unused_imports, clippy::doc_markdown, clippy::struct_excessive_bools)]\n\
         #![allow(clippy::too_many_lines, clippy::too_many_arguments, clippy::wildcard_imports)]\n\
         #![allow(clippy::match_same_arms, clippy::fn_params_excessive_bools)]\n\
         \n\
         use alloc::string::String;\n\
         use alloc::vec::Vec;\n\
         \n"
    )
}

/// Rust spelling of a type, as referenced from generated code.
fn rust_ty(t: &Typed) -> String {
    match &t.ty {
        Ty::Bool => "bool".into(),
        Ty::Int => "i32".into(),
        Ty::Decimal => "crate::types::Decimal".into(),
        Ty::Str => "String".into(),
        Ty::DateTime => "crate::types::DateTime".into(),
        Ty::AnyJson => "serde_json::Value".into(),
        Ty::Named(n) if n == "CustomData" => "crate::types::CustomData".into(),
        Ty::Named(n) => n.clone(),
        Ty::List(inner) => format!("Vec<{}>", rust_ty(inner)),
    }
}

/// The parameter type a constructor or setter takes, plus the conversion applied to it.
///
/// Accepting `impl Into<…>` for the types with obvious conversions is what makes
/// `ChargingStation::new("Model-1", "ACME")` compile.
fn arg_ty(t: &Typed) -> (String, &'static str) {
    match &t.ty {
        Ty::Str => ("impl Into<String>".into(), ".into()"),
        Ty::DateTime => ("impl Into<crate::types::DateTime>".into(), ".into()"),
        Ty::Decimal => ("impl Into<crate::types::Decimal>".into(), ".into()"),
        Ty::List(inner) if matches!(inner.ty, Ty::Str) => (
            "impl IntoIterator<Item = impl Into<String>>".into(),
            ".into_iter().map(Into::into).collect()",
        ),
        _ => (rust_ty(t), ""),
    }
}

fn field_ty(f: &crate::model::Field) -> String {
    let base = rust_ty(&f.typed);
    if f.required {
        base
    } else {
        format!("Option<{base}>")
    }
}

// ---------------------------------------------------------------------------
// enums
// ---------------------------------------------------------------------------

pub fn enums(version: VersionId, model: &VersionModel) -> String {
    let mut out = preamble(&format!(
        "Enumerations defined by {}, generated from the official JSON schemas.",
        version.label()
    ));
    out.push_str("use crate::ocpp_enum;\n\n");

    for def in model.enums.values() {
        out.push_str(&render_enum(version, def));
        out.push('\n');
    }
    out
}

fn render_enum(version: VersionId, def: &EnumDef) -> String {
    let mut out = String::new();
    out.push_str("ocpp_enum! {\n");
    let doc = doc_lines(def.doc.as_deref(), "    ");
    if doc.is_empty() {
        let _ = writeln!(
            out,
            "    /// The {} `{}` enumeration.",
            version.label(),
            def.name
        );
    } else {
        out.push_str(&doc);
    }
    let _ = writeln!(out, "    {} {{", def.name);
    for v in &def.variants {
        let _ = writeln!(out, "        /// `{}`.", v.wire);
        let _ = writeln!(out, "        {} = {:?},", v.rust, v.wire);
    }
    out.push_str("    }\n}\n");
    if let Some(d) = &def.default {
        if let Some(v) = def.variants.iter().find(|v| &v.wire == d) {
            let _ = writeln!(
                out,
                "\nimpl Default for {} {{\n    /// Schema default: `{}`.\n    fn default() -> Self {{\n        Self::{}\n    }}\n}}",
                def.name, d, v.rust
            );
        }
    }
    out
}

// ---------------------------------------------------------------------------
// structs
// ---------------------------------------------------------------------------

pub fn types(version: VersionId, model: &VersionModel) -> String {
    let mut out = preamble(&format!(
        "Data types shared between {} messages, generated from the official JSON schemas.",
        version.label()
    ));
    out.push_str("use serde::{Deserialize, Serialize};\n\n");
    out.push_str("use super::enums::*;\n");
    out.push_str("use crate::validate::{self, Validate, ValidationPath, Violations};\n\n");

    for def in model.structs.values() {
        let note = format!("The {} `{}` data type.", version.label(), def.name);
        out.push_str(&render_struct(def, Some(&note)));
        out.push('\n');
    }
    out
}

/// Emits one struct plus its constructor, builder setters and [`Validate`] impl.
fn render_struct(def: &StructDef, spec: Option<&str>) -> String {
    let mut out = String::new();
    let required: Vec<_> = def.fields.iter().filter(|f| f.required).collect();
    let optional: Vec<_> = def.fields.iter().filter(|f| !f.required).collect();
    let ordered: Vec<_> = required.iter().chain(optional.iter()).copied().collect();

    out.push_str(&doc_lines(def.doc.as_deref(), ""));
    if let Some(spec) = spec {
        if def.doc.is_some() {
            out.push_str("///\n");
        }
        let _ = writeln!(out, "/// {spec}");
    }
    let derives = if required.is_empty() {
        "#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]"
    } else {
        "#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]"
    };
    let _ = writeln!(out, "{derives}");
    let _ = writeln!(out, "pub struct {} {{", def.name);
    for f in &ordered {
        let doc = doc_lines(f.doc.as_deref(), "    ");
        if doc.is_empty() {
            let _ = writeln!(out, "    /// The `{}` member.", f.json);
        } else {
            out.push_str(&doc);
        }
        if let Some(d) = &f.default {
            let _ = writeln!(out, "    /// Schema default: `{d}`.");
        }
        let bare = f.rust.trim_start_matches("r#");
        if bare != f.json {
            let _ = writeln!(out, "    #[serde(rename = {:?})]", f.json);
        }
        if !f.required {
            out.push_str("    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n");
        }
        let _ = writeln!(out, "    pub {}: {},", f.rust, field_ty(f));
    }
    out.push_str("}\n\n");

    // ---- constructor + builder setters ------------------------------------
    let _ = writeln!(out, "impl {} {{", def.name);
    if required.is_empty() {
        let _ = writeln!(
            out,
            "    /// Creates an empty `{}`. Every field of this type is optional.\n    #[must_use]\n    pub fn new() -> Self {{\n        Self::default()\n    }}\n",
            def.name
        );
    } else {
        let args = required
            .iter()
            .map(|f| format!("{}: {}", f.rust, arg_ty(&f.typed).0))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "    /// Creates a `{}` from its required fields.\n    #[must_use]\n    pub fn new({args}) -> Self {{",
            def.name
        );
        out.push_str("        Self {\n");
        for f in &required {
            match arg_ty(&f.typed).1 {
                "" => {
                    let _ = writeln!(out, "            {},", f.rust);
                }
                convert => {
                    let _ = writeln!(out, "            {}: {}{convert},", f.rust, f.rust);
                }
            }
        }
        for f in &optional {
            let _ = writeln!(out, "            {}: None,", f.rust);
        }
        out.push_str("        }\n    }\n\n");
    }
    for f in &optional {
        let bare = f.rust.trim_start_matches("r#");
        let (arg, convert) = arg_ty(&f.typed);
        let _ = writeln!(
            out,
            "    /// Sets the optional `{}` field.\n    #[must_use]\n    pub fn with_{bare}(mut self, value: {arg}) -> Self {{\n        self.{} = Some(value{convert});\n        self\n    }}\n",
            f.json, f.rust
        );
    }
    out.push_str("}\n\n");

    // ---- validation --------------------------------------------------------
    let mut body = String::new();
    for f in &ordered {
        let accessor = format!("self.{}", f.rust);
        let statements = validate_value(&accessor, &f.typed, f.required, 2);
        if statements.trim().is_empty() {
            continue;
        }
        let _ = writeln!(body, "        path.push_key({:?});", f.json);
        body.push_str(&statements);
        body.push_str("        path.pop();\n");
    }
    let path_param = if body.contains("path") {
        "path"
    } else {
        "_path"
    };
    let out_param = if body.contains("out") { "out" } else { "_out" };
    let _ = writeln!(out, "impl Validate for {} {{", def.name);
    let _ = writeln!(
        out,
        "    fn validate_at(&self, {path_param}: &mut ValidationPath, {out_param}: &mut Violations) {{"
    );
    out.push_str(&body);
    out.push_str("    }\n}\n");
    out
}

/// Emits the validation statements for one value, unwrapping `Option` when needed.
fn validate_value(accessor: &str, t: &Typed, required: bool, depth: usize) -> String {
    let ind = "    ".repeat(depth);
    if required {
        return validate_inner(accessor, false, t, depth);
    }
    let inner = validate_inner("value", true, t, depth + 1);
    if inner.trim().is_empty() {
        return String::new();
    }
    format!("{ind}if let Some(value) = &{accessor} {{\n{inner}{ind}}}\n")
}

fn validate_inner(expr: &str, by_ref: bool, t: &Typed, depth: usize) -> String {
    let ind = "    ".repeat(depth);
    let deref = if by_ref { "*" } else { "" };
    let amp = if by_ref { "" } else { "&" };
    let c = &t.c;
    let opt = |v: Option<u32>| v.map_or("None".to_string(), |n| format!("Some({n})"));
    let optf = |v: Option<f64>| v.map_or("None".to_string(), |n| format!("Some({n:?})"));
    match &t.ty {
        Ty::Str => {
            if c.max_length.is_none() && c.min_length.is_none() {
                String::new()
            } else {
                format!(
                    "{ind}validate::string({expr}.as_str(), {}, {}, path, out);\n",
                    opt(c.min_length),
                    opt(c.max_length)
                )
            }
        }
        Ty::Int => {
            if c.minimum.is_none() && c.maximum.is_none() {
                String::new()
            } else {
                format!(
                    "{ind}validate::int_range(i64::from({deref}{expr}), {}, {}, path, out);\n",
                    optf(c.minimum),
                    optf(c.maximum)
                )
            }
        }
        Ty::Decimal => {
            if c.minimum.is_none() && c.maximum.is_none() {
                String::new()
            } else {
                format!(
                    "{ind}validate::range({expr}.get(), {}, {}, path, out);\n",
                    optf(c.minimum),
                    optf(c.maximum)
                )
            }
        }
        Ty::Bool | Ty::DateTime | Ty::AnyJson => String::new(),
        Ty::Named(_) => format!("{ind}Validate::validate_at({amp}{expr}, path, out);\n"),
        Ty::List(item) => {
            let mut s = String::new();
            if c.min_items.is_some() || c.max_items.is_some() {
                let _ = writeln!(
                    s,
                    "{ind}validate::list_len({expr}.len(), {}, {}, path, out);",
                    opt(c.min_items),
                    opt(c.max_items)
                );
            }
            let inner = validate_inner("item", true, item, depth + 2);
            if !inner.trim().is_empty() {
                let _ = write!(
                    s,
                    "{ind}for (index, item) in {expr}.iter().enumerate() {{\n{ind}    path.push_index(index);\n{inner}{ind}    path.pop();\n{ind}}}\n"
                );
            }
            s
        }
    }
}

// ---------------------------------------------------------------------------
// messages
// ---------------------------------------------------------------------------

pub fn messages(version: VersionId, model: &VersionModel) -> String {
    let mut out = preamble(&format!(
        "Request and response payloads for every {} action.",
        version.label()
    ));
    out.push_str("use serde::{Deserialize, Serialize};\n\n");
    out.push_str("use super::action::Action;\n");
    out.push_str("use super::enums::*;\n");
    out.push_str("use super::types::*;\n");
    out.push_str("use crate::message::{Confirmed, MessageKind, Origin, Request, Response, Sealed, Unconfirmed};\n");
    out.push_str("use crate::validate::{self, Validate, ValidationPath, Violations};\n\n");

    for msg in &model.messages {
        let spec = spec_note(version, msg);
        out.push_str(&render_struct(&msg.request, Some(&spec)));
        out.push('\n');
        let _ = writeln!(out, "impl Sealed for {} {{}}", msg.request.name);
        let response_ty = match &msg.response {
            Some(r) => r.name.clone(),
            None => "crate::message::NoResponse".to_string(),
        };
        let _ = writeln!(
            out,
            "impl Request for {} {{\n    type Action = Action;\n    const ACTION: Action = Action::{};\n    const KIND: MessageKind = MessageKind::{};\n    const ORIGIN: Origin = Origin::{};\n    type Response = {response_ty};\n}}\n",
            msg.request.name,
            msg.variant,
            msg.kind.ident(),
            msg.origin.ident(),
        );

        // `Confirmed` / `Unconfirmed` are what make `Handle::call` and `Handle::send`
        // impossible to mix up: an action has a response or it does not, and the schemas say
        // which.
        if let Some(resp) = &msg.response {
            let _ = writeln!(out, "impl Confirmed for {} {{}}\n", msg.request.name);
            out.push_str(&render_struct(resp, Some(&spec)));
            out.push('\n');
            let _ = writeln!(out, "impl Sealed for {} {{}}", resp.name);
            let _ = writeln!(out, "impl Response for {} {{}}\n", resp.name);
        } else {
            let _ = writeln!(out, "impl Unconfirmed for {} {{}}\n", msg.request.name);
        }
    }
    out
}

fn spec_note(version: VersionId, msg: &MessageDef) -> String {
    let block = block_name(version, msg.block);
    let kind = match msg.kind {
        Kind::Call => "CALL",
        Kind::Send => "SEND (unconfirmed, never answered — Part 4 §4.2.4)",
    };
    let dir = match msg.origin {
        Origin::ChargingStation => "Charging Station → CSMS",
        Origin::Csms => "CSMS → Charging Station",
        Origin::Both => "either direction",
    };
    format!("Spec: {} · {block} · {dir} · {kind}.", version.label())
}

// ---------------------------------------------------------------------------
// action enum + dispatch unions
// ---------------------------------------------------------------------------

pub fn action(version: VersionId, model: &VersionModel) -> String {
    let mut out = preamble(&format!(
        "The {} action set, and the direction-aware payload unions used for dispatch.",
        version.label()
    ));
    out.push_str("use serde::{Deserialize, Serialize};\n\n");
    out.push_str("use super::messages::*;\n");
    out.push_str("use crate::message::{MessageKind, Origin};\n");
    out.push_str("use crate::validate::{Validate, ValidationPath, Violations};\n");
    out.push_str("use crate::decode::{DecodeError, DecodeOptions};\n");
    out.push_str("use serde_json::value::RawValue;\n\n");

    // ---- Action ------------------------------------------------------------
    let _ = writeln!(
        out,
        "/// Every action defined by {}.\n///\n/// The variants are ordered as in the specification's action index.",
        version.label()
    );
    out.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    out.push_str("#[non_exhaustive]\npub enum Action {\n");
    for m in &model.messages {
        let _ = writeln!(
            out,
            "    /// `{}` — {}.",
            m.action,
            block_name(version, m.block)
        );
        let _ = writeln!(out, "    {},", m.variant);
    }
    out.push_str("}\n\n");

    out.push_str("impl Action {\n");
    out.push_str("    /// Every action of this version, in specification order.\n");
    out.push_str("    pub const ALL: &'static [Action] = &[\n");
    for m in &model.messages {
        let _ = writeln!(out, "        Action::{},", m.variant);
    }
    out.push_str("    ];\n\n");

    out.push_str("    /// The action name as it appears on the wire.\n    #[must_use]\n    pub const fn as_str(self) -> &'static str {\n        match self {\n");
    for m in &model.messages {
        let _ = writeln!(out, "            Action::{} => {:?},", m.variant, m.action);
    }
    out.push_str("        }\n    }\n\n");

    out.push_str("    /// Parses a wire action name. Returns `None` for actions this version does not define.\n    #[must_use]\n    pub fn from_wire(name: &str) -> Option<Self> {\n        Some(match name {\n");
    for m in &model.messages {
        let _ = writeln!(out, "            {:?} => Action::{},", m.action, m.variant);
    }
    out.push_str("            _ => return None,\n        })\n    }\n\n");

    out.push_str("    /// Whether this action is a `CALL` or an unconfirmed `SEND`.\n    #[must_use]\n    pub const fn kind(self) -> MessageKind {\n");
    let sends: Vec<_> = model
        .messages
        .iter()
        .filter(|m| m.kind == Kind::Send)
        .collect();
    if sends.is_empty() {
        out.push_str("        MessageKind::Call\n    }\n\n");
    } else {
        out.push_str("        match self {\n");
        for m in &sends {
            let _ = writeln!(
                out,
                "            Action::{} => MessageKind::Send,",
                m.variant
            );
        }
        out.push_str("            _ => MessageKind::Call,\n        }\n    }\n\n");
    }

    out.push_str("    /// Which peer originates this action.\n    #[must_use]\n    pub const fn origin(self) -> Origin {\n        match self {\n");
    for m in &model.messages {
        let _ = writeln!(
            out,
            "            Action::{} => Origin::{},",
            m.variant,
            m.origin.ident()
        );
    }
    out.push_str("        }\n    }\n\n");

    out.push_str("    /// The functional block (2.x) or feature profile (1.6) this action belongs to.\n    #[must_use]\n    pub const fn block(self) -> &'static str {\n        match self {\n");
    for m in &model.messages {
        let _ = writeln!(out, "            Action::{} => {:?},", m.variant, m.block);
    }
    out.push_str("        }\n    }\n}\n\n");

    out.push_str(
        "impl crate::message::ActionName for Action {\n    fn all() -> &'static [Self] {\n        Self::ALL\n    }\n    fn as_str(&self) -> &'static str {\n        Action::as_str(*self)\n    }\n    fn from_wire(name: &str) -> Option<Self> {\n        Action::from_wire(name)\n    }\n    fn kind(&self) -> MessageKind {\n        Action::kind(*self)\n    }\n    fn origin(&self) -> Origin {\n        Action::origin(*self)\n    }\n    fn block(&self) -> &'static str {\n        Action::block(*self)\n    }\n}\n\n",
    );

    out.push_str(
        "impl core::fmt::Display for Action {\n    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {\n        f.write_str(self.as_str())\n    }\n}\n\n\
         impl core::str::FromStr for Action {\n    type Err = crate::message::UnknownAction;\n    fn from_str(s: &str) -> Result<Self, Self::Err> {\n        Self::from_wire(s).ok_or(crate::message::UnknownAction)\n    }\n}\n\n\
         impl Serialize for Action {\n    fn serialize<S: serde::Serializer>(&self, ser: S) -> Result<S::Ok, S::Error> {\n        ser.serialize_str(self.as_str())\n    }\n}\n\n\
         impl<'de> Deserialize<'de> for Action {\n    fn deserialize<D: serde::Deserializer<'de>>(de: D) -> Result<Self, D::Error> {\n        let s = <&str as Deserialize>::deserialize(de)?;\n        Self::from_wire(s).ok_or_else(|| serde::de::Error::custom(\"unknown OCPP action\"))\n    }\n}\n\n",
    );

    // ---- payload transcoding ----------------------------------------------
    out.push_str(
        "impl Action {\n    /// Whether this action is answered at all.\n    ///\n    /// `false` only for a `SEND` (OCPP 2.1 `NotifyPeriodicEventStream`).\n    #[must_use]\n    pub const fn has_response(self) -> bool {\n        matches!(self.kind(), MessageKind::Call)\n    }\n}\n\n",
    );
    out.push_str(
        "/// Decodes a request payload into its typed form and serializes it back.\n///\n/// The round trip is the strongest cheap check that the generated types cover a payload\n/// completely: anything the types do not model is missing from the output. It backs\n/// `ocpp-cli validate` and the schema conformance suite.\npub fn transcode_request(\n    action: Action,\n    payload: &RawValue,\n    options: &DecodeOptions,\n) -> Result<alloc::boxed::Box<RawValue>, DecodeError> {\n    match action {\n",
    );
    for m in &model.messages {
        let _ = writeln!(
            out,
            "        Action::{} => crate::decode::transcode::<{}>(payload, options),",
            m.variant, m.request.name
        );
    }
    out.push_str("    }\n}\n\n");

    out.push_str(
        "/// Decodes a response payload into its typed form and serializes it back.\n///\n/// Returns [`DecodeError::unsupported_action`] for a `SEND`, which has no response.\npub fn transcode_response(\n    action: Action,\n    payload: &RawValue,\n    options: &DecodeOptions,\n) -> Result<alloc::boxed::Box<RawValue>, DecodeError> {\n    match action {\n",
    );
    for m in &model.messages {
        match &m.response {
            Some(r) => {
                let _ = writeln!(
                    out,
                    "        Action::{} => crate::decode::transcode::<{}>(payload, options),",
                    m.variant, r.name
                );
            }
            None => {
                let _ = writeln!(
                    out,
                    "        Action::{} => Err(DecodeError::unsupported_action({:?})),",
                    m.variant, m.action
                );
            }
        }
    }
    out.push_str("    }\n}\n\n");

    // ---- dispatch unions ---------------------------------------------------
    let cs_req: Vec<_> = model
        .messages
        .iter()
        .filter(|m| m.origin.from_cs())
        .collect();
    let csms_req: Vec<_> = model
        .messages
        .iter()
        .filter(|m| m.origin.from_csms())
        .collect();

    out.push_str(&union(
        "CsRequest",
        &format!(
            "A request originated by the **Charging Station** (CS → CSMS) in {}.",
            version.label()
        ),
        &cs_req,
        Kase::Request,
    ));
    out.push_str(&union(
        "CsResponse",
        &format!(
            "The CSMS's answer to a [`CsRequest`] (CSMS → CS) in {}.\n///\n/// `SEND`-only actions have no response and are therefore absent from this enum.",
            version.label()
        ),
        &cs_req,
        Kase::Response,
    ));
    out.push_str(&union(
        "CsmsRequest",
        &format!(
            "A request originated by the **CSMS** (CSMS → CS) in {}.",
            version.label()
        ),
        &csms_req,
        Kase::Request,
    ));
    out.push_str(&union(
        "CsmsResponse",
        &format!(
            "The Charging Station's answer to a [`CsmsRequest`] (CS → CSMS) in {}.",
            version.label()
        ),
        &csms_req,
        Kase::Response,
    ));
    out
}

#[derive(Clone, Copy, PartialEq)]
enum Kase {
    Request,
    Response,
}

fn union(name: &str, doc: &str, msgs: &[&MessageDef], kase: Kase) -> String {
    let members: Vec<&MessageDef> = msgs
        .iter()
        .filter(|m| kase == Kase::Request || m.response.is_some())
        .copied()
        .collect();
    let payload = |m: &MessageDef| -> String {
        match kase {
            Kase::Request => m.request.name.clone(),
            Kase::Response => m.response.as_ref().expect("filtered").name.clone(),
        }
    };

    let mut out = String::new();
    let _ = writeln!(out, "/// {doc}");
    // Payload sizes differ by two orders of magnitude across 91 actions; boxing the large
    // ones would make every `match` arm awkward for no real gain.
    out.push_str("#[derive(Clone, Debug, PartialEq)]\n#[non_exhaustive]\n#[allow(clippy::large_enum_variant)]\n");
    let _ = writeln!(out, "pub enum {name} {{");
    for m in &members {
        let _ = writeln!(out, "    /// `{}`.", m.action);
        let _ = writeln!(out, "    {}({}),", m.variant, payload(m));
    }
    out.push_str("}\n\n");

    let _ = writeln!(out, "impl {name} {{");
    out.push_str("    /// The action this payload belongs to.\n    #[must_use]\n    pub const fn action(&self) -> Action {\n        match self {\n");
    for m in &members {
        let _ = writeln!(
            out,
            "            Self::{}(_) => Action::{},",
            m.variant, m.variant
        );
    }
    out.push_str("        }\n    }\n\n");

    out.push_str(
        "    /// Decodes a raw JSON payload for `action`, classifying every failure so the\n    /// caller can answer with the correct OCPP error code.\n    pub fn decode(\n        action: Action,\n        payload: &RawValue,\n        options: &DecodeOptions,\n    ) -> Result<Self, DecodeError> {\n        Ok(match action {\n",
    );
    for m in &members {
        let _ = writeln!(
            out,
            "            Action::{} => Self::{}(crate::decode::decode_payload::<{}>(payload, options)?),",
            m.variant,
            m.variant,
            payload(m)
        );
    }
    out.push_str(
        "            other => return Err(DecodeError::unsupported_action(other.as_str())),\n        })\n    }\n\n",
    );

    out.push_str("    /// Serializes the payload object (without the OCPP-J frame).\n    pub fn to_json(&self) -> Result<alloc::string::String, serde_json::Error> {\n        match self {\n");
    for m in &members {
        let _ = writeln!(
            out,
            "            Self::{}(p) => serde_json::to_string(p),",
            m.variant
        );
    }
    out.push_str("        }\n    }\n}\n\n");

    let _ = writeln!(out, "impl Validate for {name} {{");
    out.push_str("    fn validate_at(&self, path: &mut ValidationPath, out: &mut Violations) {\n        match self {\n");
    for m in &members {
        let _ = writeln!(
            out,
            "            Self::{}(p) => p.validate_at(path, out),",
            m.variant
        );
    }
    out.push_str("        }\n    }\n}\n\n");

    let _ = writeln!(out, "impl serde::Serialize for {name} {{");
    out.push_str("    fn serialize<S: serde::Serializer>(&self, ser: S) -> Result<S::Ok, S::Error> {\n        match self {\n");
    for m in &members {
        let _ = writeln!(
            out,
            "            Self::{}(p) => p.serialize(ser),",
            m.variant
        );
    }
    out.push_str("        }\n    }\n}\n\n");
    out
}

// ---------------------------------------------------------------------------
// module root
// ---------------------------------------------------------------------------

pub fn module(version: VersionId, model: &VersionModel) -> String {
    let cs = model.messages.iter().filter(|m| m.origin.from_cs()).count();
    let csms = model
        .messages
        .iter()
        .filter(|m| m.origin.from_csms())
        .count();
    let mut out = String::new();
    let _ = write!(
        out,
        "{HEADER}\n\
         //! {label} messages, generated from the official OCA JSON schemas.\n\
         //!\n\
         //! * {n} actions ({cs} originated by the Charging Station, {csms} by the CSMS)\n\
         //! * [`Action`] names every action; [`CsRequest`] / [`CsmsRequest`] are the\n\
         //!   direction-aware unions the engine dispatches on.\n\
         //! * Every payload implements [`Validate`](crate::validate::Validate); the engine runs it\n\
         //!   after deserialization and maps failures to the right OCPP error code.\n\
         \n\
         mod action;\n\
         mod enums;\n\
         mod messages;\n\
         mod types;\n\
         \n\
         pub use action::{{\n\
         \x20   Action, CsRequest, CsResponse, CsmsRequest, CsmsResponse, transcode_request,\n\
         \x20   transcode_response,\n\
         }};\n\
         pub use enums::*;\n\
         pub use messages::*;\n\
         pub use types::*;\n",
        label = version.label(),
        n = model.messages.len(),
    );
    out
}
